(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],toast=$('#toast'),serve=$('#serveBtn'),hint=$('#hint');
const AS={raw:'assets/raw-patty.png',cook:'assets/cooking-patty.png',ready:'assets/cooked-patty.png',burn:'assets/burned-patty.png',bacon:'assets/bacon-raw.png',baconReady:'assets/bacon-crispy.png'};
const RECIPES=[
 ['Classic Burger',5.5,['bunBottom','patty','lettuceL','tomatoL','sauceL','bunTop'],'Burger + lettuce + tomato'],
 ['Cheeseburger',6.25,['bunBottom','patty','cheese','lettuceL','tomatoL','sauceL','bunTop'],'Cheeseburger + lettuce + tomato'],
 ['Bacon Cheeseburger',7.5,['bunBottom','patty','cheese','bacon','lettuceL','tomatoL','sauceL','bunTop'],'Bacon cheeseburger'],
 ['Pickle Burger',6,['bunBottom','patty','pickleL','onionL','sauceL','bunTop'],'Burger + pickles + onion'],
 ['Loaded Burger',8,['bunBottom','patty','cheese','lettuceL','tomatoL','onionL','pickleL','bacon','sauceL','bunTop'],'Loaded burger']
].map(([name,price,layers,display])=>({name,price,layers,display}));
const PEOPLE=[
 ['Lou','#f0b081','#5a2d1b','#bf4c38','#7d281d','swoop'],['Maya','#d89263','#221711','#2f3036','#121317','bun'],['Eddie','#925633','#161413','#73777c','#252a30','cap'],['Nora','#edc09a','#edc173','#416f53','#24432f','long'],['Gus','#c78559','#5a392b','#65717d','#303842','cap2']
].map(([name,skin,hair,shirt,accent,style])=>({name,skin,hair,shirt,accent,style}));
const S={money:0,score:0,combo:0,served:0,perfect:0,shift:0,time:94,orders:[],built:[],selected:null,grills:Array(6).fill(null),last:performance.now(),mistakes:0};
const R=x=>({bunBottom:'bottom bun',bunTop:'top bun',patty:'patty',cheese:'cheese',lettuceL:'lettuce',tomatoL:'tomato',onionL:'onion',pickleL:'pickles',bacon:'bacon',sauceL:'sauce'}[x]||x);
function svg(p,i){const {skin,hair,shirt,accent,style}=p,cap=style.startsWith('cap')?`<path d="M58 45q26-28 57 0v18H58z" fill="${accent}"/><path d="M96 48q32 0 43 10-18 8-43 6z" fill="${accent}"/>`:'',long=style==='long'?`<path d="M43 70q-4 70 22 95h72q26-23 18-95-5-45-56-45S48 33 43 70z" fill="${hair}"/>`:'',bun=style==='bun'?`<circle cx="103" cy="30" r="25" fill="${hair}"/>`:'',swoop=style==='swoop'?`<path d="M52 59q11-43 62-37 30 3 42 30-27-14-47-7-24 9-57 14z" fill="${hair}"/>`:'';return `<svg viewBox="0 0 200 220"><defs><linearGradient id="s${i}" x1="0" x2="1"><stop stop-color="${shirt}"/><stop offset="1" stop-color="${accent}"/></linearGradient></defs>${long}${bun}${swoop}<path d="M34 219q7-73 67-73t66 73z" fill="url(#s${i})" stroke="#0005" stroke-width="5"/><path d="M77 145q4 24 24 25 21 0 25-25" fill="${skin}"/><ellipse cx="101" cy="91" rx="48" ry="58" fill="${skin}" stroke="#0003" stroke-width="4"/>${cap}${style==='bun'?`<path d="M53 73q8-48 52-44 37 4 45 45-24-12-45-6-26 7-52 5z" fill="${hair}"/>`:''}${style.startsWith('cap')?`<path d="M59 74q4-29 43-30 34 1 42 29-28-12-42-7-25 6-43 8z" fill="${hair}" opacity=".75"/>`:''}${style==='long'?`<path d="M53 70q5-38 46-39 39 1 48 39-29-15-50-8-22 7-44 8z" fill="${hair}"/>`:''}<ellipse cx="83" cy="91" rx="5" ry="7" fill="#1d1713"/><ellipse cx="119" cy="91" rx="5" ry="7" fill="#1d1713"/><path d="M88 116q13 11 27 0" fill="none" stroke="#7b3c2f" stroke-width="5" stroke-linecap="round"/><path d="M69 81q12-7 24-2M110 79q12-5 24 3" fill="none" stroke="${hair}" stroke-width="4" stroke-linecap="round"/><ellipse cx="66" cy="103" rx="8" ry="5" fill="#e8877a55"/><ellipse cx="136" cy="103" rx="8" ry="5" fill="#e8877a55"/></svg>`}
function flash(m){toast.textContent=m;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),850)}
const recipe=()=>RECIPES[Math.floor(Math.random()*RECIPES.length)];
const order=(p)=>({person:p,recipe:recipe(),patience:100,wantsDrink:Math.random()<.45,wantsFries:Math.random()<.35});
function renderCustomers(){const h=$('#customers');h.innerHTML=S.orders.map((o,i)=>`<div class="customerCard ${i?'':'active'}"><div class="bubble ${i?'waiting':''}"><div class="bubbleTitle"><span>${i?'UP NEXT':'ORDER NOW'}</span><span>${o.person.name}</span></div><div class="bubbleOrder">${o.recipe.display}${o.wantsFries?' + fries':''}${o.wantsDrink?' + drink':''}</div><div class="miniPat"><i></i></div></div><div class="avatar">${svg(o.person,i)}</div></div>`).join('');updatePatience()}
function updatePatience(){$$('.miniPat i').forEach((b,i)=>b.style.width=(S.orders[i]?.patience||0)+'%')}
const needed=()=>S.orders[0]?.recipe.layers[S.built.length];
function renderPrep(){$$('.ingredient').forEach(b=>b.classList.remove('next'));const id={bunBottom:'buns',bunTop:'buns',patty:'patties',cheese:'cheese',lettuceL:'lettuce',tomatoL:'tomato',onionL:'onion',pickleL:'pickles',bacon:'bacon',sauceL:'sauce'}[needed()];if(id)$(`[data-item="${id}"]`)?.classList.add('next')}
function renderStack(){const h=$('#burgerStack');h.innerHTML='';let y=0;S.built.forEach(l=>{const d=document.createElement('div');d.className='layer '+l;d.style.bottom=(y+4)+'px';h.appendChild(d);y+=({bunBottom:18,patty:20,cheese:12,lettuceL:10,tomatoL:10,onionL:8,pickleL:8,bacon:9,sauceL:5,bunTop:25}[l]||10)})}
function updateHUD(){const o=S.orders[0],n=needed();$('#money').textContent='$'+S.money.toFixed(2);$('#score').textContent=S.score;$('#combo').textContent='x'+Math.max(1,S.combo);$('#served').textContent=S.shift+'/10';$('#shiftFill').style.width=Math.min(100,S.shift*10)+'%';$('#time').textContent=Math.max(0,Math.ceil(S.time));$('#perfect').textContent=S.perfect+'/10';$('#perfectFooter').textContent=S.combo>1?`${S.combo} clean orders in a row`:'Keep the streak alive';hint.textContent=n?(n==='patty'||n==='bacon'?`Cook ${R(n)} until green, then tap it to stack.`:`Next: add ${R(n)}.`):'Burger complete — finish any ordered fries/drink, then serve.';serve.disabled=!!n||(!$('#drinkBtn').classList.contains('done')&&o?.wantsDrink)||(!$('#friesBtn').classList.contains('done')&&o?.wantsFries);updatePatience()}
function syncBuild(){renderPrep();renderStack();updateHUD()}
function cold(type){if(needed()===type){S.built.push(type);S.selected=null;flash(`${R(type)} added`)}else{S.mistakes++;flash(`Not yet — next is ${R(needed())}`)}syncBuild()}
function choose(item){if(item==='buns')return cold(needed()==='bunTop'?'bunTop':'bunBottom');if(item==='patties'||item==='bacon'){S.selected=item==='patties'?'patty':'bacon';return flash(`Tap an empty grill spot for ${R(S.selected)}`)}const m={cheese:'cheese',lettuce:'lettuceL',tomato:'tomatoL',onion:'onionL',pickles:'pickleL',sauce:'sauceL'};if(m[item])cold(m[item])}
function bg(type,stage){return type==='patty'?`url(${stage==='raw'?AS.raw:stage==='ready'?AS.ready:stage==='burned'?AS.burn:AS.cook})`:`url(${stage==='ready'?AS.baconReady:AS.bacon})`}
function renderGrills(now){$$('.grillSlot').forEach((el,i)=>{const g=S.grills[i],sp=el.querySelector('.foodSprite'),bar=el.querySelector('.slotBar i');el.className='grillSlot';if(!g){sp.style.backgroundImage='none';bar.style.width='0';return}const e=now-g.start,cook=g.type==='patty'?4600:3400,burn=cook+(g.type==='patty'?4200:3400);g.stage=e>=burn?'burned':e>=cook?'ready':e<500?'raw':'cooking';sp.style.backgroundImage=bg(g.type,g.stage);bar.style.width=Math.min(100,e/cook*100)+'%';bar.style.background=g.stage==='ready'?'#58df3b':g.stage==='burned'?'#f14c37':'#efaa2e';if(g.stage==='ready')el.classList.add('ready');if(g.stage==='burned')el.classList.add('burned')})}
function grill(i){const g=S.grills[i];if(!g){if(!S.selected)return flash('Select patties or bacon first');S.grills[i]={type:S.selected,start:performance.now(),stage:'raw'};flash(`${R(S.selected)} on the grill`);S.selected=null;return}if(g.stage==='ready'){if(needed()===g.type){S.built.push(g.type);S.grills[i]=null;flash(`${R(g.type)} stacked`);syncBuild()}else flash(`Hold that — next is ${R(needed())}`)}else if(g.stage==='burned'){S.grills[i]=null;S.mistakes++;flash('Burned! Tossed it.')}else flash('Still cooking…')}
function resetExtras(){$('#drinkBtn').classList.remove('done');$('#friesBtn').classList.remove('done')}
function nextOrder(){S.orders.shift();S.orders.push(order(PEOPLE[(S.served+4)%PEOPLE.length]));S.built=[];S.grills=Array(6).fill(null);S.selected=null;S.mistakes=0;resetExtras();renderCustomers();syncBuild()}
function finish(){const o=S.orders[0],clean=S.mistakes===0,perfect=clean&&o.patience>68;S.combo=clean?S.combo+1:0;S.perfect+=perfect?1:0;const pts=Math.round(o.patience)+(perfect?40:clean?15:0),tip=(.8+o.patience/55)*(S.combo>=4?1.3:S.combo>=2?1.15:1);S.money+=o.recipe.price+(o.wantsDrink?1.5:0)+(o.wantsFries?2:0)+tip;S.score+=pts;S.served++;S.shift++;flash(perfect?`PERFECT! +${pts}`:`Served! +${pts}`);if(S.shift>=10){S.shift=0;S.time=94;flash(`Shift complete — $${S.money.toFixed(2)} earned!`)}nextOrder()}
$$('.ingredient').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.item)));$$('.grillSlot').forEach((b,i)=>b.addEventListener('click',()=>grill(i)));
$('#drinkBtn').addEventListener('click',function(){if(!S.orders[0].wantsDrink)return flash('No drink on this order');this.classList.add('done');flash('Drink ready!');updateHUD()});
$('#friesBtn').addEventListener('click',function(){if(!S.orders[0].wantsFries)return flash('No fries on this order');this.classList.add('done');flash('Fries ready!');updateHUD()});serve.addEventListener('click',finish);
function tick(now){const dt=Math.min(.1,(now-S.last)/1000);S.last=now;S.time-=dt;S.orders.forEach((o,i)=>o.patience=Math.max(0,o.patience-dt*(i?0.25:2.5)));if(S.orders[0]?.patience<=0){S.combo=0;flash('Customer left!');nextOrder()}if(S.time<=0){S.time=94;S.shift=0;flash('New shift started!')}renderGrills(now);updateHUD();requestAnimationFrame(tick)}
S.orders=PEOPLE.map(order);renderCustomers();syncBuild();requestAnimationFrame(tick);
})();