(()=>{
'use strict';
const $=s=>document.querySelector(s);
const canvas=$('#kitchenCanvas'),ctx=canvas.getContext('2d');
const toast=$('#toast'),serveBtn=$('#serveBtn');
const ASSETS={bottomBun:'assets/bottom-bun.png',topBun:'assets/top-bun.png',pattyRaw:'assets/raw-patty.png',pattyCooking:'assets/cooking-patty.png',pattyCooked:'assets/cooked-patty.png',pattyBurned:'assets/burned-patty.png',baconRaw:'assets/bacon-raw.png',baconCooking:'assets/bacon-raw.png',baconCooked:'assets/bacon-crispy.png',cheese:'assets/cheese.png',sauce:'assets/sauce-drizzle.png'};
const IMAGES={};
function loadImages(){return Promise.all(Object.entries(ASSETS).map(([k,src])=>new Promise(res=>{const im=new Image();im.onload=()=>{IMAGES[k]=im;res()};im.onerror=()=>{IMAGES[k]=null;res()};im.src=src+'?v=4'})))}
const CATALOG={patty:{id:'patty',label:'PATTY',raw:'pattyRaw',cooking:'pattyCooking',cooked:'pattyCooked',burned:'pattyBurned',cookMs:5200,burnMs:6500,stack:{w:176,h:53,overlap:18}},bacon:{id:'bacon',label:'BACON',raw:'baconRaw',cooking:'baconCooking',cooked:'baconCooked',burned:'baconCooked',cookMs:3900,burnMs:5200,stack:{w:178,h:40,overlap:17}},cheese:{id:'cheese',label:'CHEESE',asset:'cheese',stack:{w:184,h:40,overlap:19}},sauce:{id:'sauce',label:'SAUCE',asset:'sauce',stack:{w:162,h:28,overlap:22}},topBun:{id:'topBun',label:'BUNS',asset:'topBun',stack:{w:190,h:80,overlap:20}},bottomBun:{id:'bottomBun',label:'BUNS',asset:'bottomBun',stack:{w:190,h:62,overlap:0}}};
const RECIPES={hamburger:{price:4,request:'One hamburger with burger sauce, please!',layers:['bottomBun','patty','sauce','topBun']},cheeseburger:{price:4.75,request:'One cheeseburger with burger sauce, please!',layers:['bottomBun','patty','cheese','sauce','topBun']},baconCheese:{price:5.75,request:'One bacon cheeseburger with burger sauce, please!',layers:['bottomBun','patty','cheese','sauce','bacon','topBun']}};
const CUSTOMERS=[['Lou','🧑'],['Maya','👩'],['Eddie','🧔'],['Tina','👩‍🦱'],['Sam','👨'],['Nora','👩‍🦰'],['Gus','🧑‍🦱'],['Penny','👨‍🦱'],['Bea','👵'],['Dex','🤠']];
const state={money:0,score:0,served:0,patience:100,recipe:RECIPES.cheeseburger,built:[],selectedSource:null,selectedCooked:null,grill:[null,null],customerIndex:0,last:performance.now()};const hits=[];
function flash(m){toast.textContent=m;toast.classList.add('show');clearTimeout(flash.t);flash.t=setTimeout(()=>toast.classList.remove('show'),1000)}function needed(){return state.recipe.layers[state.built.length]}function isComplete(){return state.built.length===state.recipe.layers.length&&state.built.every((x,i)=>x===state.recipe.layers[i])}function setHUD(){$('#money').textContent=state.money.toFixed(2);$('#score').textContent=state.score;$('#served').textContent=state.served;$('#patience').textContent=Math.round(state.patience);$('#patfill').style.width=state.patience+'%';serveBtn.classList.toggle('ready',isComplete())}function newOrder(){const ks=Object.keys(RECIPES);state.recipe=RECIPES[ks[Math.floor(Math.random()*ks.length)]];state.built=[];state.grill=[null,null];state.selectedSource=null;state.selectedCooked=null;state.patience=100;const c=CUSTOMERS[state.customerIndex++%CUSTOMERS.length];$('#customerName').textContent=c[0];$('#customerEmoji').textContent=c[1];$('#orderText').textContent=state.recipe.request;setHUD()}
function fit(img,x,y,w,h){if(!img)return false;const r=Math.min(w/img.width,h/img.height),dw=img.width*r,dh=img.height*r;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh);return true}function rr(x,y,w,h,r,f,s){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=f;ctx.fill();if(s){ctx.strokeStyle=s;ctx.lineWidth=3;ctx.stroke()}}function text(t,x,y,z=22,a='center'){ctx.fillStyle='#eee';ctx.font=`900 ${z}px Arial`;ctx.textAlign=a;ctx.textBaseline='middle';ctx.fillText(t,x,y)}function hit(id,x,y,w,h,d={}){hits.push({id,x,y,w,h,...d})}
function bin(id,label,asset,x,y,w,h){rr(x,y,w,h,14,'#d8dcda','#777');fit(IMAGES[asset],x+12,y+7,w-24,h-34);ctx.fillStyle='#f4f2ebee';ctx.fillRect(x,y+h-28,w,28);ctx.fillStyle='#333';ctx.font='900 17px Arial';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h-9);hit(id,x,y,w,h)}
function bunBin(x,y,w,h){rr(x,y,w,h,14,'#d8dcda','#777');const top=IMAGES.topBun,bottom=IMAGES.bottomBun;/* draw each bun in its own guaranteed box so neither can disappear behind the label */fit(top,x+25,y+4,w-50,35);fit(bottom,x+27,y+38,w-54,25);ctx.fillStyle='#f4f2ebf2';ctx.fillRect(x,y+h-25,w,25);ctx.fillStyle='#333';ctx.font='900 17px Arial';ctx.textAlign='center';ctx.fillText('BUNS',x+w/2,y+h-8);hit('coldBun',x,y,w,h)}
function grill(i,x,y,w,h){rr(x,y,w,h,12,'#202323','#777');for(let j=0;j<6;j++){ctx.fillStyle=j%2?'#3a3d3c':'#111';ctx.fillRect(x+j*w/6,y,w/12,h)}const g=state.grill[i];if(g){const d=CATALOG[g.type],e=performance.now()-g.started;g.stage=e>d.cookMs+d.burnMs?'burned':e>d.cookMs?'cooked':'raw';fit(IMAGES[g.stage==='raw'?d.raw:g.stage==='cooked'?d.cooked:d.burned],x+18,y+12,w-36,h-24);if(g.stage==='cooked'){ctx.strokeStyle='#65d25c';ctx.lineWidth=6;ctx.strokeRect(x+5,y+5,w-10,h-10)}}hit('grill',x,y,w,h,{i})}
function burger(){let y=318;for(const id of state.built){const d=CATALOG[id],s=d.stack;y-=s.h;let a=d.asset;if(id==='patty')a='pattyCooked';if(id==='bacon')a='baconCooked';fit(IMAGES[a],1040-s.w/2,y,s.w,s.h);y+=s.overlap}hit('assembly',820,100,440,245)}
function render(){ctx.clearRect(0,0,1600,420);hits.length=0;ctx.fillStyle='#121413';ctx.fillRect(0,0,1600,420);text('🔥 GRILL',28,34,26,'left');text('🍽️ ASSEMBLY',655,34,26,'left');grill(0,30,65,270,165);grill(1,315,65,270,165);bin('patty','PATTY','pattyRaw',32,278,240,112);bin('bacon','BACON','baconRaw',310,278,240,112);rr(650,58,725,332,16,'#b98857','#6c4b32');ctx.beginPath();ctx.ellipse(1040,322,260,55,0,0,Math.PI*2);ctx.fillStyle='#e9e9e9';ctx.fill();ctx.strokeStyle='#8d9090';ctx.lineWidth=4;ctx.stroke();ctx.beginPath();ctx.ellipse(1040,315,185,34,0,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();burger();rr(1405,55,175,335,15,'#b9bfbd','#666');bunBin(1420,75,145,88);bin('cheese','CHEESE','cheese',1420,175,145,88);bin('sauce','SAUCE','sauce',1420,275,145,88)}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*1600/r.width,y:(e.clientY-r.top)*420/r.height}}function pick(p){return [...hits].reverse().find(h=>p.x>=h.x&&p.x<=h.x+h.w&&p.y>=h.y&&p.y<=h.y+h.h)}function addBun(){const n=needed();if(n==='bottomBun'||n==='topBun'){state.built.push(n);flash(n==='bottomBun'?'Bottom bun placed':'Top bun placed')}else flash(`Next: ${CATALOG[n]?.label||n}`)}function addCold(id){if(needed()===id){state.built.push(id);flash(CATALOG[id].label+' added')}else flash(`Next: ${CATALOG[needed()]?.label||needed()}`)}
canvas.addEventListener('pointerdown',e=>{const h=pick(point(e));if(!h)return;if(h.id==='patty'||h.id==='bacon'){state.selectedSource=h.id;flash(h.id+' selected')}else if(h.id==='grill'){const g=state.grill[h.i];if(!g&&state.selectedSource){state.grill[h.i]={type:state.selectedSource,started:performance.now(),stage:'raw'};state.selectedSource=null}else if(g&&g.stage==='cooked'){state.selectedCooked=h.i;flash('Cooked '+g.type+' selected')}else if(g&&g.stage==='burned')state.grill[h.i]=null}else if(h.id==='coldBun')addBun();else if(h.id==='cheese')addCold('cheese');else if(h.id==='sauce')addCold('sauce');else if(h.id==='assembly'&&state.selectedCooked!==null){const g=state.grill[state.selectedCooked];if(g&&needed()===g.type){state.built.push(g.type);state.grill[state.selectedCooked]=null;state.selectedCooked=null;flash(g.type+' added')}}});
serveBtn.addEventListener('click',()=>{if(!isComplete())return flash(`Finish burger — next: ${CATALOG[needed()]?.label||needed()}`);const tip=1+state.patience/50;state.money+=state.recipe.price+tip;state.score+=Math.round(state.patience);state.served++;flash('Served!');setTimeout(newOrder,650)});function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=1600*d;canvas.height=420*d;canvas.style.aspectRatio='1600/420';ctx.setTransform(d,0,0,d,0,0)}function tick(n){const dt=Math.min(100,n-state.last);state.last=n;state.patience=Math.max(0,state.patience-dt*.0018);if(state.patience<=0)newOrder();setHUD();render();requestAnimationFrame(tick)}window.addEventListener('resize',resize);resize();loadImages().then(()=>{newOrder();requestAnimationFrame(tick)});
})();