(()=>{
const q=id=>document.getElementById(id);
const G={patty:{stage:'empty',timers:[]},bacon:{stage:'empty',timers:[]}};
let rawPick=null,cookedPick=null;
const grillEl=q('grill'), patty=q('grillPatty');
patty.className='dualFood dualPatty'; patty.setAttribute('aria-label','Patty grill spot');
let bacon=q('grillBacon'); if(!bacon){bacon=document.createElement('span');bacon.id='grillBacon';bacon.className='dualFood dualBacon';grillEl.appendChild(bacon)}
let rb=q('rawBacon'); if(!rb){rb=document.createElement('button');rb.id='rawBacon';rb.className='rawBaconBin';rb.innerHTML='<span class="rawBaconVisual"></span><span class="meatBinLabel">BACON</span>';document.querySelector('.kitchen .station').appendChild(rb)}
if(!q('raw').querySelector('.pattyLabel')){let l=document.createElement('span');l.className='meatBinLabel pattyLabel';l.textContent='PATTY';q('raw').appendChild(l)}
const shelf=document.querySelector('.foodShelf'); let sauce=q('sauce'); if(!sauce){sauce=document.createElement('button');sauce.id='sauce';sauce.className='foodItem sauceItem';sauce.innerHTML='<span class="sauceBottle"></span><span class="foodLabel">SAUCE</span>';shelf.appendChild(sauce)}
const css=document.createElement('style');css.textContent=`
.kitchen{grid-template-columns:36% 64%!important}.prepStation{padding-right:34%!important}.prepStation .board{left:3%!important;right:36%!important;top:14%!important;bottom:6%!important}.foodShelf{right:2%!important;top:12%!important;bottom:6%!important;width:32%!important;padding:3%!important;gap:3%!important}.foodItem{min-height:0;overflow:hidden}.foodLabel{font-size:clamp(10px,1.15vw,16px)!important;bottom:3%!important;z-index:9!important}.plate{width:72%!important;height:25%!important;bottom:7%!important}
.grill{overflow:hidden!important}.grill:before{content:"";position:absolute;left:50%;top:7%;bottom:7%;width:2px;background:#888;opacity:.7}.rawbin{left:4%!important;width:38%!important;background:linear-gradient(#eee,#c7cac6)!important}.rawbin:before{content:"";position:absolute;inset:10% 13% 18%;background:url('assets/raw-patty.png') center/contain no-repeat}.rawBaconBin{position:absolute;right:4%;bottom:4%;width:38%;height:20%;border:3px solid #777;border-radius:7px;background:linear-gradient(#eee,#c7cac6);display:flex;align-items:center;justify-content:center;overflow:hidden}.rawBaconBin.selected,.rawbin.selected{outline:4px solid #f1ca51!important}.meatBinLabel{position:absolute;left:0;right:0;bottom:1px;text-align:center;font-size:10px;font-weight:950;color:#333;z-index:5}.rawBaconVisual{width:72%;height:38%;border-radius:18px 8px;background:repeating-linear-gradient(92deg,#8e211b 0 9%,#d65339 10% 18%,#f0aa88 19% 25%,#b62f24 26% 36%,#efb08e 37% 44%,#8b211d 45% 56%);border:1px solid #651b17;box-shadow:0 6px 0 -1px #b53428,0 11px 0 -2px #8b251e,0 4px 6px #0006;transform:rotate(-4deg)}
.dualFood{position:absolute;display:none;z-index:5;background-repeat:no-repeat!important;background-position:center!important;background-size:contain!important;border:0!important;box-shadow:none!important}.dualFood.ready{filter:drop-shadow(0 0 8px #78e35f)}.dualFood.chosen{filter:drop-shadow(0 0 11px #ffd95a)}.dualPatty{left:8%;top:18%;width:34%;height:64%}.dualPatty.raw{background-image:url('assets/raw-patty.png')!important}.dualPatty.cooking{background-image:url('assets/cooking-patty.png')!important}.dualPatty.ready{background-image:url('assets/cooked-patty.png')!important}.dualPatty.burned{background-image:url('assets/burned-patty.png')!important}.dualBacon{right:5%;top:25%;width:42%;height:50%;border-radius:15px 8px}.dualBacon.raw{background:repeating-linear-gradient(92deg,#9d2820 0 8%,#df6044 9% 18%,#f2b091 19% 25%,#b5362b 26% 37%,#f0bea0 38% 44%,#97261f 45% 56%)!important}.dualBacon.cooking{background:repeating-linear-gradient(92deg,#7f211b 0 8%,#c24d35 9% 18%,#df8e6d 19% 25%,#9a2a23 26% 37%,#df9879 38% 44%,#752019 45% 56%)!important}.dualBacon.ready{background:repeating-linear-gradient(92deg,#651a16 0 8%,#a63728 9% 18%,#c66d50 19% 25%,#7d211c 26% 37%,#cf8062 38% 44%,#591814 45% 56%)!important}.dualBacon.burned{background:#38201b!important}
.foodItem#bun:before{content:"";position:absolute;inset:4% 5% 23%;background:url('assets/buns-stock.png') center/contain no-repeat!important}.foodItem#cheese:before{content:"";position:absolute;inset:5% 6% 22%;background:url('assets/cheese-stock.png') center/contain no-repeat!important;transform:none!important;clip-path:none!important}.sauceBottle{position:absolute;left:17%;right:17%;top:7%;height:60%;border-radius:50%;background:radial-gradient(circle at 45% 35%,#ffc67a 0 14%,#e7923b 40%,#b95e1e 75%);box-shadow:inset 5px 3px #fff4,0 5px 7px #0004}.sauceBottle:before{content:"";position:absolute;left:18%;right:18%;top:18%;height:16%;border-radius:50%;border-top:5px solid #ffd39a;transform:rotate(-12deg)}
.plateBun{width:78%!important;height:42%!important;bottom:1%!important;background:transparent!important;border:0!important;box-shadow:none!important;z-index:30!important}.plateBun:before{content:"";position:absolute;left:50%;bottom:0;transform:translateX(-50%);width:66%;height:62%;background:url('assets/bottom-bun.png') center bottom/contain no-repeat!important}.plateBun.readyTarget:before{filter:drop-shadow(0 0 10px #ffd94d)}
#layers .layer{left:50%!important;transform:translateX(-50%)!important;width:61%!important;border:0!important;box-shadow:none!important;background-repeat:no-repeat!important;background-position:center bottom!important;background-size:contain!important}#layers .patty{height:24%!important;background-image:url('assets/cooked-patty.png')!important}#layers .cheese{height:20%!important;background-image:url('assets/cheese.png')!important;clip-path:none!important}#layers .sauce{width:48%!important;height:6%!important;background:repeating-linear-gradient(10deg,transparent 0 8%,#e98f35 9% 17%,#ffc06e 18% 24%,#df842f 25% 34%,transparent 35% 44%)!important;border-radius:50%!important}#layers .bacon{width:56%!important;height:9%!important;background:repeating-linear-gradient(92deg,#6b1d17 0 10%,#b74430 11% 20%,#d98060 21% 28%,#84251d 29% 40%)!important;border-radius:12px!important;transform:translateX(-50%) rotate(-2deg)!important}#layers .topBun{width:64%!important;height:28%!important;background-image:url('assets/top-bun.png')!important}
`;
document.head.appendChild(css);
function target(){if(order==='bacon')return ['bottomBun','patty','cheese','sauce','bacon','topBun'];if(order==='cheese')return ['bottomBun','patty','cheese','sauce','topBun'];return ['bottomBun','patty','sauce','topBun']}
function need(){return target()[built.length]} function el(t){return t==='patty'?patty:bacon} function timersOff(t){G[t].timers.forEach(clearTimeout);G[t].timers=[]}
function draw(t){const e=el(t),s=G[t].stage;e.className='dualFood '+(t==='patty'?'dualPatty':'dualBacon')+(s==='empty'?'':' '+s)+(cookedPick===t?' chosen':'');e.style.display=s==='empty'?'none':'block'}
function cook(t){if(G[t].stage!=='empty')return flash((t==='patty'?'Patty':'Bacon')+' already on grill');G[t].stage='raw';draw(t);const ready=t==='patty'?5800:3900,burn=t==='patty'?7000:6000;G[t].timers.push(setTimeout(()=>{if(G[t].stage==='raw'){G[t].stage='cooking';draw(t)}},t==='patty'?1200:700));G[t].timers.push(setTimeout(()=>{if(G[t].stage==='raw'||G[t].stage==='cooking'){G[t].stage='ready';draw(t);flash(t+' ready!')}},ready));G[t].timers.push(setTimeout(()=>{if(G[t].stage==='ready'){G[t].stage='burned';if(cookedPick===t)cookedPick=null;draw(t)}},ready+burn))}
function choose(t){if(G[t].stage==='burned'){timersOff(t);G[t].stage='empty';draw(t);return flash('Burned '+t+' tossed')}if(G[t].stage!=='ready')return flash('Wait until the '+t+' is ready');cookedPick=t;draw('patty');draw('bacon');q('plateBun').classList.add('readyTarget');flash('Tap the burger to add the '+t)}
function render2(){const h=q('layers');h.innerHTML='';let y=13;built.forEach(x=>{if(x==='bottomBun')return;let d=document.createElement('div');d.className='layer '+x;d.style.bottom=y+'%';h.appendChild(d);y+=x==='patty'?5:x==='cheese'?3:x==='sauce'?2:x==='bacon'?3:0});q('cust').classList.toggle('readyToServe',JSON.stringify(built)===JSON.stringify(target()))}
function reset2(){['patty','bacon'].forEach(t=>{timersOff(t);G[t].stage='empty';draw(t)});rawPick=null;cookedPick=null;q('raw').classList.remove('selected');rb.classList.remove('selected')}
function next2(){built=['bottomBun'];render2();reset2();let r=Math.random();order=r<.42?'cheese':r<.68?'plain':'bacon';let i=served%names.length;q('name').textContent=names[i];q('cust').textContent=people[i];q('order').textContent=order==='bacon'?'One bacon cheeseburger with burger sauce, please!':order==='cheese'?'One cheeseburger with burger sauce, please!':'One hamburger with burger sauce, please!';patience=100;clearInterval(timer);timer=setInterval(()=>{patience=Math.max(0,patience-.7);q('patnum').textContent=Math.round(patience);q('patbar').style.width=patience+'%';if(!patience){clearInterval(timer);served++;hud();flash('Customer left!');setTimeout(next2,700)}},300)}
q('raw').onclick=()=>{rawPick='patty';q('raw').classList.add('selected');rb.classList.remove('selected');flash('Patty selected — tap grill')};rb.onclick=()=>{rawPick='bacon';rb.classList.add('selected');q('raw').classList.remove('selected');flash('Bacon selected — tap grill')};grillEl.onclick=e=>{if(e.target===patty||e.target===bacon)return;if(!rawPick)return flash('Select patty or bacon first');let t=rawPick;rawPick=null;q('raw').classList.remove('selected');rb.classList.remove('selected');cook(t)};patty.onclick=e=>{e.stopPropagation();choose('patty')};bacon.onclick=e=>{e.stopPropagation();choose('bacon')};
q('plateBun').onclick=()=>{if(!cookedPick)return flash('Select a cooked item first');if(need()!==cookedPick)return flash('That is not next');let t=cookedPick;cookedPick=null;timersOff(t);G[t].stage='empty';draw(t);built.push(t);render2();q('plateBun').classList.remove('readyTarget')};q('cheese').onclick=()=>{if(need()!=='cheese')return flash(order==='plain'?'No cheese on this order':'Add patty first');built.push('cheese');render2()};sauce.onclick=()=>{if(need()!=='sauce')return flash('Finish the earlier ingredients first');built.push('sauce');render2()};q('bun').onclick=()=>{if(need()!=='topBun')return flash('Finish the fillings first');built.push('topBun');render2();flash('Burger finished!')};q('cust').onclick=()=>{if(JSON.stringify(built)!==JSON.stringify(target()))return flash('Finish the burger first');clearInterval(timer);let base=order==='plain'?4:order==='cheese'?4.75:5.75,earn=base+2+patience/50;money+=earn;score+=Math.round(patience);served++;hud();flash('Served! +$'+earn.toFixed(2));setTimeout(next2,700)};clearTimeout(gt);next2();
})();