(()=>{
const q=id=>document.getElementById(id);
const G={patty:{stage:'empty',timers:[]},bacon:{stage:'empty',timers:[]}};
let rawPick=null,cookedPick=null;
const grillEl=q('grill'), patty=q('grillPatty');
patty.className='dualFood dualPatty'; patty.setAttribute('aria-label','Patty grill spot');
let bacon=q('grillBacon'); if(!bacon){bacon=document.createElement('span');bacon.id='grillBacon';bacon.className='dualFood dualBacon';grillEl.appendChild(bacon)}
let rb=q('rawBacon'); if(!rb){rb=document.createElement('button');rb.id='rawBacon';rb.className='rawBaconBin';rb.innerHTML='<span class="rawBaconVisual"></span><span class="meatBinLabel">BACON</span>';document.querySelector('.kitchen .station').appendChild(rb)}
if(!q('raw').querySelector('.pattyLabel')){let l=document.createElement('span');l.className='meatBinLabel pattyLabel';l.textContent='PATTY';q('raw').appendChild(l)}
const shelf=document.querySelector('.foodShelf'); let sauce=q('sauce'); if(!sauce){sauce=document.createElement('button');sauce.id='sauce';sauce.className='foodItem sauceItem';sauce.innerHTML='<span class="sauceBottle"></span><span class="foodLabel">SAUCE</span>';shelf.appendChild(sauce)}
const css=document.createElement('style');css.textContent=`
.kitchen{grid-template-columns:36% 64%!important}.prepStation{padding-right:34%!important}.prepStation .board{left:3%!important;right:36%!important;top:14%!important;bottom:6%!important}.foodShelf{right:2%!important;top:12%!important;bottom:6%!important;width:32%!important;padding:3%!important;gap:3%!important}.foodItem{min-height:0}.foodLabel{font-size:clamp(10px,1.15vw,16px)!important;bottom:3%!important;z-index:9!important}.plate{width:72%!important;height:25%!important;bottom:7%!important}
.grill{overflow:hidden!important}.grill:before{content:"";position:absolute;left:50%;top:7%;bottom:7%;width:2px;background:#888;opacity:.7}.rawbin{left:4%!important;width:38%!important}.rawBaconBin{position:absolute;right:4%;bottom:4%;width:38%;height:20%;border:3px solid #777;border-radius:7px;background:linear-gradient(#eee,#c7cac6);display:flex;align-items:center;justify-content:center;overflow:hidden}.rawBaconBin.selected,.rawbin.selected{outline:4px solid #f1ca51!important}.meatBinLabel{position:absolute;left:0;right:0;bottom:1px;text-align:center;font-size:10px;font-weight:950;color:#333}.rawBaconVisual{width:68%;height:34%;border-radius:14px 7px;background:repeating-linear-gradient(92deg,#8b211d 0 8%,#d9583e 9% 18%,#f0a586 19% 25%,#b72e26 26% 37%,#f0b596 38% 44%,#8b211d 45% 56%);border:1px solid #651b17;box-shadow:0 7px 0 -1px #a82c24,0 14px 0 -2px #7d211c,0 4px 6px #0006;transform:rotate(-5deg)}
.dualFood{position:absolute;display:none;z-index:5}.dualFood.ready{filter:drop-shadow(0 0 8px #78e35f)}.dualFood.chosen{filter:drop-shadow(0 0 11px #ffd95a)}.dualPatty{left:8%;top:20%;width:34%;height:60%;border-radius:49%;border:2px solid #342018}.dualPatty.raw{background:#c65350}.dualPatty.cooking{background:#8a4834}.dualPatty.ready{background:#593126}.dualPatty.burned{background:#211715}.dualBacon{right:6%;top:32%;width:39%;height:34%;border-radius:15px 8px;border:1px solid #601b16}.dualBacon.raw{background:repeating-linear-gradient(92deg,#9d2820 0 8%,#df6044 9% 18%,#f2b091 19% 25%)}.dualBacon.cooking{background:repeating-linear-gradient(92deg,#7f211b 0 8%,#c24d35 9% 18%,#df8e6d 19% 25%)}.dualBacon.ready{background:repeating-linear-gradient(92deg,#651a16 0 8%,#a63728 9% 18%,#c66d50 19% 25%)}.dualBacon.burned{background:#38201b}
.foodItem#bun:before{content:"";position:absolute;left:13%;right:13%;top:14%;height:48%;background:radial-gradient(circle at 30% 25%,#fff2bf 0 2%,transparent 3%),radial-gradient(circle at 60% 20%,#fff2bf 0 2%,transparent 3%),linear-gradient(#efa94e,#c97624);border:2px solid #9b5b22;border-radius:70px 70px 10px 10px;box-shadow:inset 0 4px #fff3,0 4px 5px #0004}.foodItem#cheese:before{content:"";position:absolute;left:18%;right:18%;top:20%;height:38%;background:#f5b51b;transform:rotate(-8deg);border:2px solid #d28b08;clip-path:polygon(0 10%,100% 0,92% 80%,50% 100%,7% 78%);box-shadow:0 4px 5px #0004}.sauceBottle{position:absolute;left:30%;right:30%;top:12%;height:50%;border-radius:10px 10px 18px 18px;background:linear-gradient(90deg,#d97f2b,#f1ad50,#d77c28);border:2px solid #a75c20}.sauceBottle:before{content:"";position:absolute;left:28%;right:28%;top:-14%;height:18%;background:#eee4d4;border:1px solid #999}
.plateBun{width:72%!important;height:35%!important;bottom:5%!important;background:transparent!important;border:0!important;box-shadow:none!important;z-index:30!important}.plateBun:before{content:"";position:absolute;left:50%;bottom:17%;transform:translateX(-50%);width:72%;height:29%;border:2px solid #9b652f;border-radius:8px 8px 28px 28px;background:linear-gradient(#e9b365,#c97f2d);box-shadow:inset 0 3px #fff3,0 4px 5px #0005}.plateBun.readyTarget:before{outline:5px solid #ffda55;box-shadow:0 0 18px #ffd94d}
#layers .layer{left:50%!important;transform:translateX(-50%)!important;width:52%!important;border:0!important;box-shadow:0 3px 4px #0004}#layers .patty{height:9%!important;background:repeating-linear-gradient(10deg,#4c281f 0 8px,#6b3829 9px 15px)!important;border-radius:18px!important}#layers .cheese{height:6%!important;background:#f4b51d!important;clip-path:polygon(0 5%,100% 0,92% 70%,72% 62%,55% 100%,38% 67%,12% 76%)!important}#layers .sauce{width:46%!important;height:3.5%!important;background:repeating-linear-gradient(12deg,transparent 0 8%,#e98f35 9% 17%,#ffc06e 18% 25%,#df842f 26% 34%,transparent 35% 44%)!important;border-radius:50%!important}#layers .bacon{height:6%!important;background:repeating-linear-gradient(95deg,#6b1d17 0 10%,#b74430 11% 20%,#d98060 21% 28%,#84251d 29% 40%)!important;border-radius:12px!important;transform:translateX(-50%) rotate(-2deg)!important}#layers .topBun{height:15%!important;background:radial-gradient(circle at 30% 28%,#fff0b0 0 2%,transparent 3%),radial-gradient(circle at 55% 18%,#fff0b0 0 2%,transparent 3%),radial-gradient(circle at 72% 35%,#fff0b0 0 2%,transparent 3%),linear-gradient(#eca64b,#c97827)!important;border:2px solid #9b5b22!important;border-radius:80px 80px 12px 12px!important}
`;
document.head.appendChild(css);
function target(){if(order==='bacon')return ['bottomBun','patty','cheese','sauce','bacon','topBun'];if(order==='cheese')return ['bottomBun','patty','cheese','sauce','topBun'];return ['bottomBun','patty','sauce','topBun']}
function need(){return target()[built.length]} function el(t){return t==='patty'?patty:bacon} function timersOff(t){G[t].timers.forEach(clearTimeout);G[t].timers=[]}
function draw(t){const e=el(t),s=G[t].stage;e.className='dualFood '+(t==='patty'?'dualPatty':'dualBacon')+(s==='empty'?'':' '+s)+(cookedPick===t?' chosen':'');e.style.display=s==='empty'?'none':'block'}
function cook(t){if(G[t].stage!=='empty')return flash((t==='patty'?'Patty':'Bacon')+' already on grill');G[t].stage='raw';draw(t);const ready=t==='patty'?5800:3900,burn=t==='patty'?7000:6000;G[t].timers.push(setTimeout(()=>{if(G[t].stage==='raw'){G[t].stage='cooking';draw(t)}},t==='patty'?1200:700));G[t].timers.push(setTimeout(()=>{if(G[t].stage==='raw'||G[t].stage==='cooking'){G[t].stage='ready';draw(t);flash(t+' ready!')}},ready));G[t].timers.push(setTimeout(()=>{if(G[t].stage==='ready'){G[t].stage='burned';if(cookedPick===t)cookedPick=null;draw(t)}},ready+burn))}
function choose(t){if(G[t].stage==='burned'){timersOff(t);G[t].stage='empty';draw(t);return flash('Burned '+t+' tossed')}if(G[t].stage!=='ready')return flash('Wait until the '+t+' is ready');cookedPick=t;draw('patty');draw('bacon');q('plateBun').classList.add('readyTarget');flash('Tap the burger to add the '+t)}
function render2(){const h=q('layers');h.innerHTML='';let y=25;built.forEach(x=>{if(x==='bottomBun')return;let d=document.createElement('div');d.className='layer '+x;d.style.bottom=y+'%';h.appendChild(d);y+=x==='patty'?7:x==='cheese'?4:x==='sauce'?2.5:x==='bacon'?4.5:0});q('cust').classList.toggle('readyToServe',JSON.stringify(built)===JSON.stringify(target()))}
function reset2(){['patty','bacon'].forEach(t=>{timersOff(t);G[t].stage='empty';draw(t)});rawPick=null;cookedPick=null;q('raw').classList.remove('selected');rb.classList.remove('selected')}
function next2(){built=['bottomBun'];render2();reset2();let r=Math.random();order=r<.42?'cheese':r<.68?'plain':'bacon';let i=served%names.length;q('name').textContent=names[i];q('cust').textContent=people[i];q('order').textContent=order==='bacon'?'One bacon cheeseburger with burger sauce, please!':order==='cheese'?'One cheeseburger with burger sauce, please!':'One hamburger with burger sauce, please!';patience=100;clearInterval(timer);timer=setInterval(()=>{patience=Math.max(0,patience-.7);q('patnum').textContent=Math.round(patience);q('patbar').style.width=patience+'%';if(!patience){clearInterval(timer);served++;hud();flash('Customer left!');setTimeout(next2,700)}},300)}
q('raw').onclick=()=>{rawPick='patty';q('raw').classList.add('selected');rb.classList.remove('selected');flash('Patty selected — tap grill')};rb.onclick=()=>{rawPick='bacon';rb.classList.add('selected');q('raw').classList.remove('selected');flash('Bacon selected — tap grill')};grillEl.onclick=e=>{if(e.target===patty||e.target===bacon)return;if(!rawPick)return flash('Select patty or bacon first');let t=rawPick;rawPick=null;q('raw').classList.remove('selected');rb.classList.remove('selected');cook(t)};patty.onclick=e=>{e.stopPropagation();choose('patty')};bacon.onclick=e=>{e.stopPropagation();choose('bacon')};
q('plateBun').onclick=()=>{if(!cookedPick)return flash('Select a cooked item first');if(need()!==cookedPick)return flash('That is not next');let t=cookedPick;cookedPick=null;timersOff(t);G[t].stage='empty';draw(t);built.push(t);render2();q('plateBun').classList.remove('readyTarget')};q('cheese').onclick=()=>{if(need()!=='cheese')return flash(order==='plain'?'No cheese on this order':'Add patty first');built.push('cheese');render2()};sauce.onclick=()=>{if(need()!=='sauce')return flash('Finish the earlier ingredients first');built.push('sauce');render2()};q('bun').onclick=()=>{if(need()!=='topBun')return flash('Finish the fillings first');built.push('topBun');render2();flash('Burger finished!')};q('cust').onclick=()=>{if(JSON.stringify(built)!==JSON.stringify(target()))return flash('Finish the burger first');clearInterval(timer);let base=order==='plain'?4:order==='cheese'?4.75:5.75,earn=base+2+patience/50;money+=earn;score+=Math.round(patience);served++;hud();flash('Served! +$'+earn.toFixed(2));setTimeout(next2,700)};clearTimeout(gt);next2();
})();