/* Ben's Burgers 26: deterministic game state; no parallel visual-only selection state. */
(function(root){
'use strict';
const RECIPES = [
 {id:'classic',name:'Classic burger',price:5.5,layers:['bottomBun','patty','lettuce','tomato','sauce','topBun']},
 {id:'cheese',name:'Cheeseburger',price:6.25,layers:['bottomBun','patty','cheese','lettuce','tomato','sauce','topBun']},
 {id:'pickle',name:'Pickle burger',price:6,layers:['bottomBun','patty','onion','pickles','sauce','topBun']},
 {id:'bacon',name:'Bacon cheeseburger',price:7.5,layers:['bottomBun','patty','cheese','bacon','lettuce','tomato','sauce','topBun']},
 {id:'loaded',name:'Loaded burger',price:8,layers:['bottomBun','patty','cheese','bacon','lettuce','tomato','onion','pickles','sauce','topBun']}
];
const PEOPLE=['Lou','Maya','Eddie','Nora','Gus'];
const LABELS={bottomBun:'bottom bun',topBun:'top bun',patty:'patty',rawPatty:'raw patty',cheese:'cheese',bacon:'bacon',rawBacon:'raw bacon',lettuce:'lettuce',tomato:'tomato',onion:'onion',pickles:'pickles',sauce:'burger sauce'};
const count=(a,id)=>a.filter(v=>v===id).length;
const same=(a,b)=>a.length===b.length&&a.every(id=>count(a,id)===count(b,id));
class Kitchen {
 constructor(){this.shift=1;this.capacity=1;this.shiftServed=0;this.served=0;this.score=0;this.money=0;this.combo=0;this.perfect=0;this.serial=0;this.selected=null;this.grills=Array(4).fill(null);this.jobs={fries:null,drink:null};this.paused=true;this.phase='playing';this.phaseLeft=0;this.message='Welcome! Open the grill to begin.';this.orders=[this.makeOrder()];this.activeId=this.orders[0].id;}
 makeOrder(){const n=this.serial++,schedule=[1,0,2,3,4],r=RECIPES[schedule[n%5]];return{id:n+1,person:n%5,recipe:r,built:[],fries:n%3!==1,drink:n%3!==2,friesReady:false,drinkReady:false,patience:100,mistakes:0};}
 get active(){return this.orders.find(o=>o.id===this.activeId)||this.orders[0];}
 say(message,ok=true){this.message=message;return {ok,message};}
 playable(){return !this.paused&&this.phase==='playing';}
 remaining(o=this.active){return o.recipe.layers.filter((id,i,a)=>count(o.built,id)<count(a.slice(0,i+1),id));}
 canAdd(id,o=this.active){if(!o||!this.remaining(o).includes(id))return false;if(!o.built.length)return id==='bottomBun';if(id==='bottomBun'||o.built.includes('topBun'))return false;if(id==='topBun')return this.remaining(o).length===1;if(id!=='patty'&&count(o.built,'patty')<count(o.recipe.layers,'patty'))return false;return true;}
 ready(o=this.active){return !!o&&same(o.built,o.recipe.layers)&&o.built[0]==='bottomBun'&&o.built.at(-1)==='topBun'&&(!o.fries||o.friesReady)&&(!o.drink||o.drinkReady);}
 hint(){const o=this.active;if(this.phase==='served')return 'Order served! Thank you.';if(this.selected)return `${LABELS[this.selected]} selected — tap an empty grill spot.`;if(this.ready())return `Everything is ready. Tap SERVE ${PEOPLE[o.person].toUpperCase()}.`;const rem=this.remaining();if(rem.length){const id=rem.find(i=>this.canAdd(i));if(id==='patty'||id==='bacon'){const cooked=this.grills.findIndex(g=>g&&g.type===id&&this.stage(g)==='ready');if(cooked>=0)return `Tap the READY ${id} on grill ${cooked+1} to add it.`;return `Select RAW ${id==='patty'?'PATTY':'BACON'}, then tap a grill spot.`;}return `Next: ${LABELS[id]||'finish your burger'}. Tap its ingredient tray.`;}if(o.fries&&!o.friesReady)return this.jobs.fries?'Fries are at the fryer. Collect them when READY.':'Burger done. Tap the FRYER to cook the fries.';return this.jobs.drink?'Collect the drink when READY.':'Burger done. Tap the DRINK STATION to fill the cola.';}
 pick(id){if(!this.playable())return this.say('Resume the game first.',false);this.selected=null;if(id==='rawPatty'||id==='rawBacon'){this.selected=id==='rawPatty'?'patty':'bacon';return this.say(this.hint());}if(!LABELS[id])return this.say('That is not an ingredient.',false);return this.add(id);}
 add(id){if(!this.canAdd(id)){this.active.mistakes++;const has=this.active.recipe.layers.includes(id);return this.say(!has?`This burger does not need ${LABELS[id]}.`:this.hint(),false);}this.active.built.push(id);return this.say(`${LABELS[id]} added.`,true);}
 stage(g){const t=g.type==='patty'?5000:4000;return g.elapsed<t*.4?'raw':g.elapsed<t?'cooking':g.elapsed<t+10000?'ready':'burned';}
 grillTap(index){if(!this.playable())return this.say('Resume the game first.',false);if(!Number.isInteger(index)||index<0||index>=this.grills.length)return this.say('Unknown grill spot.',false);if(index===3&&this.capacity===1)return this.say('This grill spot unlocks when you expand the diner.',false);const g=this.grills[index];if(!g){if(!this.selected)return this.say('Tap RAW PATTY or RAW BACON first.',false);this.grills[index]={type:this.selected,elapsed:0};const name=this.selected;this.selected=null;return this.say(`${name} cooking on grill ${index+1}.`);}const stage=this.stage(g);if(stage==='burned'){this.grills[index]=null;this.active.mistakes++;return this.say('Burned food discarded. Cook a fresh batch.',false);}if(stage!=='ready')return this.say('Still cooking. Wait for READY.',false);this.selected=null;const result=this.add(g.type);if(result.ok)this.grills[index]=null;return result;}
 side(type){if(!this.playable())return this.say('Resume the game first.',false);if(!['fries','drink'].includes(type))return this.say('Unknown station.',false);this.selected=null;const job=this.jobs[type];if(job){if(job.elapsed<job.duration)return this.say(`${type==='fries'?'Frying':'Filling'}… wait for READY.`,false);const owner=this.orders.find(o=>o.id===job.orderId);if(owner)owner[type+'Ready']=true;this.jobs[type]=null;return this.say(`${type==='fries'?'Fries':'Drink'} added to ${owner?PEOPLE[owner.person]+'’s':'the'} order.`);}const o=this.active;if(!o[type])return this.say(`No ${type} on this order.`,false);if(o[type+'Ready'])return this.say(`${type==='fries'?'Fries':'Drink'} already on the tray.`,false);this.jobs[type]={orderId:o.id,elapsed:0,duration:type==='fries'?6000:3000};return this.say(type==='fries'?'Basket lowered. Fries are cooking.':'Cup placed. Cola is filling.');}
 undo(){if(!this.playable())return this.say('Resume the game first.',false);this.selected=null;const id=this.active.built.pop();return this.say(id?`Removed ${LABELS[id]}.`:'Nothing to undo.');}
 chooseOrder(id){if(!this.playable()||!this.orders.some(o=>o.id===id))return this.say('Order unavailable.',false);this.activeId=id;this.selected=null;return this.say(this.hint());}
 serve(){if(!this.playable())return this.say('This order is not ready to serve.',false);this.selected=null;if(!this.ready())return this.say(this.hint(),false);const o=this.active,perfect=o.mistakes===0&&o.patience>=65;this.combo=o.mistakes?0:this.combo+1;const points=Math.round(o.patience)+(perfect?40:10);this.money+=o.recipe.price+(o.fries?2:0)+(o.drink?1.5:0)+(o.patience/50)*(this.combo>=3?1.2:1);this.score+=points;this.served++;this.shiftServed++;this.perfect+=perfect?1:0;this.phase='served';this.phaseLeft=1100;return this.say(`${perfect?'Perfect order!':'Thank you!'} +${points} points`);}
 replaceOrder(id){const index=this.orders.findIndex(o=>o.id===id);if(index<0)return;this.orders[index]=this.makeOrder();for(const key of ['fries','drink'])if(this.jobs[key]?.orderId===id)this.jobs[key]=null;if(this.activeId===id)this.activeId=this.orders[index].id;this.selected=null;}
 advance(ms){if(this.paused||!Number.isFinite(ms)||ms<=0||this.phase==='summary')return;if(this.phase==='served'){this.phaseLeft-=ms;if(this.phaseLeft<=0){this.replaceOrder(this.activeId);this.phase=this.shiftServed>=5?'summary':'playing';this.say(this.phase==='summary'?'Shift complete! Take a breather.':`Hi! I’m ${PEOPLE[this.active.person]}.`);}return;}
 this.grills.forEach(g=>{if(g)g.elapsed+=ms;});Object.values(this.jobs).forEach(j=>{if(j)j.elapsed=Math.min(j.duration,j.elapsed+ms);});
 const gone=[];this.orders.forEach(o=>{o.patience=Math.max(0,o.patience-ms/(this.shift===1?1000:Math.max(650,1000-this.shift*40)));if(o.patience===0)gone.push(o.id);});gone.forEach(id=>{this.combo=0;this.replaceOrder(id);this.say('A customer left. Fresh order — try again.',false);});
 }
 continueShift(expand=false){if(this.phase!=='summary')return false;this.shift++;this.shiftServed=0;this.perfect=0;this.grills=Array(4).fill(null);this.jobs={fries:null,drink:null};if(expand&&this.shift>=3)this.capacity=Math.min(3,this.capacity+1);this.orders=[];for(let i=0;i<this.capacity;i++)this.orders.push(this.makeOrder());this.activeId=this.orders[0].id;this.phase='playing';this.paused=false;this.selected=null;this.say(`Shift ${this.shift}. ${this.capacity===1?'One customer at a time.':'Your bigger diner is open!'}`);return true;}
}
const api={Kitchen,RECIPES,PEOPLE,LABELS,same};
if(typeof module!=='undefined'&&module.exports){module.exports=api;return;}
root.BB26=api;
const A=root.BBArt,G=new Kitchen(),$=id=>document.getElementById(id);
const cache=new Map();function html(id,value){if(cache.get(id)!==value){$(id).innerHTML=value;cache.set(id,value);}}
function text(id,value){const s=String(value);if($(id).textContent!==s)$(id).textContent=s;}
function viewport(){const vv=window.visualViewport;document.documentElement.style.setProperty('--app-height',(vv?vv.height:window.innerHeight)+'px');document.documentElement.style.setProperty('--app-width',(vv?vv.width:window.innerWidth)+'px');}
viewport();window.addEventListener('resize',viewport);window.visualViewport?.addEventListener('resize',viewport);
const tray=[['bottomBun','BUN BASE'],['cheese','CHEESE'],['lettuce','LETTUCE'],['tomato','TOMATO'],['onion','ONION'],['topBun','BUN TOP'],['pickles','PICKLES'],['sauce','SAUCE'],['rawPatty','RAW PATTY'],['rawBacon','RAW BACON']];
$('ingredients').innerHTML=tray.map(([id,label])=>`<button type="button" data-action="ingredient" data-id="${id}" aria-label="${LABELS[id]}"><span class="food-art">${A.food(id)}</span><span class="tray-label">${label}</span></button>`).join('');
$('grills').innerHTML=Array.from({length:4},(_,i)=>`<button type="button" class="grill" data-action="grill" data-index="${i}" aria-label="Grill ${i+1}"><span class="grill-art"></span><span class="grill-status"></span><span class="progress"><i></i></span></button>`).join('');
let lastOrder='',lastBuild='',lastPerson=-1,lastPhase='',lastMessage='',toastTimer=null,modalMode='welcome',lastSideArt={};
function showModal(mode){modalMode=mode;G.paused=true;$('modal').hidden=false;$('app').inert=true;
 if(mode==='welcome'){text('modalTitle','Welcome to Ben’s Burgers');html('modalText','<p>One customer. One great burger.</p><p><b>1.</b> Add the bottom bun. Select raw meat, then tap the grill.<br><b>2.</b> Tap cooked meat when it says <b>READY</b>. Add the requested toppings and top bun.<br><b>3.</b> Start the fryer or drink filler when ordered; tap again to collect.<br><b>4.</b> Tap the green <b>SERVE</b> button.</p><p>Gold trays are suggested ingredients. Blue means meat is selected.</p>');text('modalPrimary','OPEN THE GRILL');}
 else if(mode==='summary'){text('modalTitle',`Shift ${G.shift} complete!`);html('modalText',`<p><b>${G.shiftServed} orders</b> served · <b>${G.perfect} perfect</b></p><p>Total earnings: $${G.money.toFixed(2)} · Score: ${G.score}</p><p>${G.shift>=2&&G.capacity<3?'Ready for a bigger store? Expansion adds another simultaneous order and a fourth grill spot. You can also keep serving one at a time.':'Keep practicing one customer at a time. Store expansion becomes available after shift 2.'}</p>`);text('modalPrimary','NEXT SHIFT');}
 else{text('modalTitle',mode==='help'?'How to run the grill':'Grill paused');html('modalText',mode==='help'?'<p>Follow the ingredient list beside the customer. The burger picture and checklist use that exact recipe.</p><p>Add a bun base, cook the patty, add toppings in any order, then cap with the top bun. Fryer and drink filler need a start tap and a collect tap. Serve only when the whole order is ready.</p><p>Undo removes your last burger layer. Nothing cooks or loses patience while paused.</p>':'<p>Your food and customer timers are paused.</p>');text('modalPrimary','RESUME');}
 $('expandBtn').hidden=mode!=='summary'||G.shift<2||G.capacity>=3;$('modalPrimary').focus();
}
function closeModal(expand=false){if(modalMode==='summary')G.continueShift(expand);else G.paused=false;$('modal').hidden=true;$('app').inert=false;lastPhase='';$('pauseBtn').focus();render();}
function notify(){if(G.message===lastMessage)return;lastMessage=G.message;text('status',G.message);$('status').classList.toggle('error',false);clearTimeout(toastTimer);}
function render(){
 const o=G.active;if(!o)return;
 text('score',G.score);text('money','$'+G.money.toFixed(2));text('shift',`${G.shift} · ${G.shiftServed}/5`);text('storeName',G.capacity===1?'CORNER STAND':G.capacity===2?'NEIGHBORHOOD DINER':'BUSY DINER');text('combo',G.combo>1?`${G.combo}× streak`:'GRILL · STACK · SERVE');
 text('personName',PEOPLE[o.person]);text('recipeName',o.recipe.name);text('orderNumber',`ORDER ${String(o.id).padStart(2,'0')}`);text('patienceLabel',`${Math.ceil(o.patience)}%`);$('patienceFill').style.width=o.patience+'%';$('patienceFill').style.background=o.patience<28?'#e56c55':o.patience<55?'#e8b346':'#79bf56';
 $('customerArt').style.backgroundPosition=(o.person*25)+'% 100%';$('customerArt').setAttribute('aria-label',PEOPLE[o.person]+' at the counter');
 if(lastPerson!==o.person){$('customerArt').classList.remove('arrive');void $('customerArt').offsetWidth;$('customerArt').classList.add('arrive');lastPerson=o.person;}
 $('customerArt').classList.toggle('happy',G.phase==='served');$('customerArt').classList.toggle('impatient',o.patience<28&&G.phase==='playing');
 $('app').classList.toggle('paused',G.paused);$('app').classList.toggle('serving',G.phase==='served');
 const orderKey=o.id+':'+o.recipe.id;if(orderKey!==lastOrder){html('orderBurger',A.burger(o.recipe.layers,true));html('orderSides',(o.fries?`<span class="side-icon">${A.fries()}</span>`:'')+(o.drink?`<span class="side-icon">${A.drink()}</span>`:''));lastOrder=orderKey;}
 html('orderTabs',G.capacity>1?G.orders.map(v=>`<button type="button" data-action="customer" data-order="${v.id}" class="${o.id===v.id?'chosen':''}">${PEOPLE[v.person]}${G.ready(v)?' ✓':''}</button>`).join(''):'');
 $('orderTabs').hidden=G.capacity===1;
 const list=o.recipe.layers.map((id,i)=>`<span data-needed="${id}" class="recipe-chip ${count(o.built,id)>=count(o.recipe.layers.slice(0,i+1),id)?'added':''}">${count(o.built,id)>=count(o.recipe.layers.slice(0,i+1),id)?'✓ ':''}${LABELS[id]}</span>`).join('');html('recipeList',list);
 text('orderExtras',(o.fries?'Fries'+(o.friesReady?' ✓':''):'No fries')+' · '+(o.drink?'Cola'+(o.drinkReady?' ✓':''):'No drink'));
 const buildKey=o.id+':'+o.built.join(',')+':'+o.friesReady+o.drinkReady;if(buildKey!==lastBuild){html('builtBurger',A.burger(o.built));html('readySides',(o.friesReady?`<span>${A.fries()}</span>`:'')+(o.drinkReady?`<span>${A.drink()}</span>`:''));lastBuild=buildKey;}
 text('buildLabel',o.built.length?`${o.built.length}/${o.recipe.layers.length} layers`:'Start with a bun base');
 document.querySelectorAll('[data-action="ingredient"]').forEach(b=>{const id=b.dataset.id,isMeat=id==='rawPatty'||id==='rawBacon',meat=id==='rawPatty'?'patty':'bacon';b.classList.toggle('suggested',isMeat?G.canAdd(meat):G.canAdd(id));b.classList.toggle('selected',isMeat&&G.selected===meat);b.setAttribute('aria-pressed',String(isMeat&&G.selected===meat));});
 document.querySelectorAll('.grill').forEach((el,i)=>{const g=G.grills[i],stage=i===3&&G.capacity===1?'locked':g?G.stage(g):'empty';el.dataset.stage=stage;el.classList.toggle('place',!!G.selected&&stage==='empty');let label=stage==='locked'?'EXPAND TO UNLOCK':stage==='empty'?(G.selected?'PLACE HERE':'GRILL '+(i+1)):stage==='ready'?'READY · TAP':stage==='burned'?'BURNED · TOSS':`${stage.toUpperCase()} ${Math.max(1,Math.ceil(((g.type==='patty'?5000:4000)-g.elapsed)/1000))}s`;el.querySelector('.grill-status').textContent=label;el.setAttribute('aria-label',`Grill ${i+1}: ${label}`);const key=g?g.type+stage:stage;if(el.dataset.art!==key){el.querySelector('.grill-art').innerHTML=g?A.food(g.type,stage):stage==='locked'?'<span class="lock-symbol">◇</span>':'';el.dataset.art=key;}el.querySelector('.progress i').style.width=g?Math.min(100,g.elapsed/(g.type==='patty'?5000:4000)*100)+'%':'0%';});
 for(const type of ['fries','drink']){const job=G.jobs[type],ready=job&&job.elapsed>=job.duration,progress=job?job.elapsed/job.duration:0,button=$(type+'Station');const state=ready?'ready':job?'working':o[type+'Ready']?'collected':'idle';button.dataset.state=state;button.style.setProperty('--fill',Math.round(progress*100)+'%');const artKey=state+':'+(type==='drink'?Math.floor(progress*10):0);if(lastSideArt[type]!==artKey){$(type+'Machine').innerHTML=A.machine(type,progress);lastSideArt[type]=artKey;}text(type+'Label',ready?'READY · COLLECT':job?(type==='fries'?'FRYING ':'FILLING ')+Math.max(1,Math.ceil((job.duration-job.elapsed)/1000))+'s':o[type+'Ready']?'ON TRAY ✓':o[type]?(type==='fries'?'START FRYER':'FILL COLA'):'NOT ORDERED');button.setAttribute('aria-label',(type==='fries'?'Fryer: ':'Drink station: ')+$(type+'Label').textContent);}
 const ready=G.ready();$('serveBtn').classList.toggle('ready',ready);$('serveBtn').setAttribute('aria-disabled',String(!ready||G.phase!=='playing'));text('serveBtn',G.phase==='served'?'SERVED ✓':`SERVE ${PEOPLE[o.person].toUpperCase()} →`);text('hint',G.hint());text('pauseBtn',G.paused?'▶':'Ⅱ');notify();
 if(G.phase==='summary'&&lastPhase!=='summary')showModal('summary');lastPhase=G.phase;
}
$('app').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;let result;switch(b.dataset.action){case 'ingredient':result=G.pick(b.dataset.id);break;case 'grill':result=G.grillTap(Number(b.dataset.index));break;case 'fries':result=G.side('fries');break;case 'drink':result=G.side('drink');break;case 'serve':result=G.serve();break;case 'undo':result=G.undo();break;case 'customer':result=G.chooseOrder(Number(b.dataset.order));break;case 'pause':showModal('pause');return;case 'help':showModal('help');return;}render();if(result&&!result.ok){$('status').classList.add('error');}});
$('modalPrimary').addEventListener('click',()=>closeModal());$('expandBtn').addEventListener('click',()=>closeModal(true));
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modal').hidden)showModal('pause');});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!G.paused)showModal('pause');});
// Model inspection is read-only; tests exercise the same DOM controls players use.
Object.defineProperty(root,'bbState',{get:()=>JSON.parse(JSON.stringify(G))});
let last=performance.now(),accum=0;function tick(now){const dt=Math.min(100,now-last);last=now;G.advance(dt);accum+=dt;if(accum>=80){render();accum=0;}requestAnimationFrame(tick);}
render();showModal('welcome');requestAnimationFrame(tick);root.__BB_VERSION__='26.0';
})(typeof globalThis!=='undefined'?globalThis:this);
