/* DOM is a view of Kitchen. One delegated handler per control surface. */
(function(root){
'use strict';
const {Kitchen,SHOP,PEOPLE,LABELS}=root.BB27,A=root.BBArt,$=id=>document.getElementById(id);
const SAVE_KEY='bens-burgers.v27.save';let saveWarning='',saveConflict=false,lastSaved='';
function load(){try{const s=localStorage.getItem(SAVE_KEY);return s?JSON.parse(s):null;}catch(e){saveWarning='Saving is unavailable in this browser. Keep this tab open.';return null;}}
const saved=load();let G;try{G=new Kitchen(saved);}catch(e){G=new Kitchen();saveWarning='The old save could not be read. A fresh stand is ready.';}
function save(){if(saveConflict)return;try{const data=JSON.stringify(G.snapshot());if(data!==lastSaved){localStorage.setItem(SAVE_KEY,data);lastSaved=data;}}catch(e){saveWarning='Progress cannot be saved in this browser. Keep this tab open.';}}
function text(id,value){const s=String(value);if($(id).textContent!==s)$(id).textContent=s;}
const cache=new Map();function html(id,value){if(cache.get(id)!==value){$(id).innerHTML=value;cache.set(id,value);}}
function viewport(){const vv=window.visualViewport;document.documentElement.style.setProperty('--app-height',(vv?vv.height:innerHeight)+'px');document.documentElement.style.setProperty('--app-width',(vv?vv.width:innerWidth)+'px');}
viewport();addEventListener('resize',viewport);window.visualViewport?.addEventListener('resize',viewport);
const tray=[['bottomBun','BUN BASE'],['rawPatty','RAW PATTY'],['topBun','BUN TOP'],['cheese','CHEESE'],['lettuce','LETTUCE'],['tomato','TOMATO'],['onion','ONION'],['pickles','PICKLES'],['sauce','SAUCE'],['rawBacon','RAW BACON']];
let lastUnlocks='',lastOrder='',lastBuild='',lastPerson=-1,lastPhase='',lastSideArt={},modalMode='welcome',shopReturn=null,shopFilter='All',shopOrigin=null,shopResult='';
$('grills').innerHTML=Array.from({length:4},(_,i)=>`<button type="button" class="grill" data-action="grill" data-index="${i}" aria-label="Burner ${i+1}"><span class="grill-art"></span><span class="grill-status"></span><span class="progress"><i></i></span></button>`).join('');
function renderIngredients(){const key=G.unlocks.join(',');if(key===lastUnlocks&&$('ingredients').children.length)return;lastUnlocks=key;const available=tray.filter(([id])=>G.hasIngredient(id));let markup=available.map(([id,label])=>`<button type="button" data-action="ingredient" data-id="${id}" aria-label="${LABELS[id]}"><span class="food-art">${A.food(id)}</span><span class="tray-label">${label}</span></button>`).join('');if(available.length<10)markup+='<button type="button" class="shop-teaser" data-action="shop"><span class="teaser-plus">+</span><span>UNLOCK<br>TOPPINGS</span></button>';$('ingredients').innerHTML=markup;const n=$('ingredients').children.length;$('ingredients').style.setProperty('--cols',n<=4?2:n<=6?3:5);$('ingredients').style.setProperty('--rows',2);}
function showModal(mode){modalMode=mode;G.paused=true;$('modal').hidden=false;$('app').inert=true;$('app').classList.add('paused');$('expandBtn').hidden=true;
 if(mode==='welcome'){text('modalTitle',G.loaded?'Welcome back!':'Start your little burger stand');html('modalText',`<p><b>Buns, patties, one burner.</b> Earn money by serving burgers, then buy every topping and extra station in the <b>SHOP</b>.</p><p>Tap the bun base. Select <b>RAW PATTY</b> and tap burner 1. When it says <b>READY</b>, tap the patty, add the top bun, then <b>SERVE</b>.</p><p>Customers only order what you own. Ingredient unlocks are permanent and supplies are unlimited. Shop time pauses cooking and patience.</p><p class="save-note">${saveWarning||'Cash, unlocks, and your current order save on this browser. In-game money only — no real purchases.'}</p>`);text('modalPrimary',G.loaded?'CONTINUE GAME':'OPEN THE GRILL');}
 else if(mode==='summary'){text('modalTitle',`Shift ${G.shift} complete!`);html('modalText',`<p><b>${G.shiftServed} burgers served</b> · ${G.perfect} perfect orders</p><p>Available cash: <b>$${G.money.toFixed(2)}</b><br>Total earned: $${(G.earnedCents/100).toFixed(2)}</p><p>Invest in an ingredient, a burner, or a new station. Your purchases stay unlocked. Larger diners are optional paid upgrades.</p>`);text('modalPrimary','NEXT SHIFT');$('expandBtn').hidden=false;text('expandBtn','VISIT UPGRADE SHOP');}
 else if(mode==='conflict'){text('modalTitle','Game opened in another tab');html('modalText','<p>This tab is paused to protect your saved cash and purchases. Reload to use the latest saved game.</p>');text('modalPrimary','LOAD LATEST SAVE');}
 else{text('modalTitle',mode==='help'?'Your stand, your pace':'Taking a breather');html('modalText',mode==='help'?'<p>Add a bun base, cook a patty, add the requested toppings, and cap it with the top bun. Tap the green named <b>SERVE</b> button.</p><p><b>SHOP:</b> unlock each ingredient once with earned cash. Burners are separate purchases. The fryer and cola fountain unlock side orders. Each machine takes a start tap and a collect tap.</p><p>You never need to buy more buns or patties. Locked items cannot appear on orders. New menu items start with new customers, not the current ticket.</p><p>After ten meals, you may buy a two-customer diner; extra customers arrive next shift. Keep the small stand as long as you like.</p>':'<p>Nothing cooks or loses patience while paused.</p><p>Use the shop to spend your earned cash on permanent upgrades.</p>');text('modalPrimary','RESUME');$('expandBtn').hidden=false;text('expandBtn','UPGRADE SHOP');}
 $('modalPrimary').focus();save();
}
function closeModal(){if(modalMode==='conflict'){location.reload();return;}if(modalMode==='summary')G.continueShift();else G.paused=false;$('modal').hidden=true;$('app').inert=false;lastPhase='';render();save();$('pauseBtn').focus();}
function openShop(id=null){if(saveConflict)return;shopOrigin=document.activeElement;shopReturn=$('modal').hidden?null:modalMode;$('modal').hidden=true;G.paused=true;$('app').inert=true;$('app').classList.add('paused');$('shopModal').hidden=false;const item=SHOP.find(x=>x.id===id);shopFilter=item?item.group:'All';shopResult='';renderShop();$('shopClose').focus();save();}
function closeShop(){if(saveConflict){$('shopModal').hidden=true;showModal('conflict');return;}$('shopModal').hidden=true;if(shopReturn)showModal(shopReturn);else{G.paused=false;$('app').inert=false;render();if(shopOrigin?.isConnected)shopOrigin.focus();else $('shopBtn').focus();}shopReturn=null;save();}
function itemArt(item){if(item.art)return A.food(item.art);if(item.id==='fryer')return A.machine('fries');if(item.id==='drinkMachine')return A.machine('drink');return `<span class="equipment-icon" aria-hidden="true">${item.id.startsWith('burner')?'◉':'⌂'}</span>`;}
function renderShop(){
 text('shopCash','$'+G.money.toFixed(2));text('shopStatus',shopResult||'One-time unlocks. Unlimited ingredients after purchase.');
 $('shopFilters').innerHTML=['All','Ingredients','Equipment','Store expansion'].map(group=>`<button type="button" data-filter="${group}" aria-pressed="${shopFilter===group}">${group}</button>`).join('');
 const items=SHOP.filter(x=>shopFilter==='All'||x.group===shopFilter);
 $('shopItems').innerHTML=items.map(item=>{const owned=G.owns(item.id),status=G.purchaseStatus(item.id);return `<article class="shop-item ${owned?'owned':''}"><div class="shop-art">${itemArt(item)}</div><div class="shop-copy"><small>${item.group}</small><h3>${item.name}</h3><p>${item.description}</p><span class="purchase-reason">${owned?'Permanently unlocked':status.ok?'Ready to unlock':status.message}</span></div><button type="button" data-buy="${item.id}" ${owned||!status.ok?'disabled':''} aria-label="${owned?item.name+' already owned':'Buy '+item.name+' for '+item.cost+' in-game dollars'}">${owned?'OWNED ✓':'BUY $'+item.cost}</button></article>`;}).join('');
}
function render(){
 const o=G.active;if(!o)return;renderIngredients();
 text('score',G.score);text('money','$'+G.money.toFixed(2));text('shift',`${G.shift} · ${G.shiftServed}/5`);text('storeName',G.capacity===1?'CORNER STAND':G.capacity===2?'NEIGHBORHOOD DINER':'BUSY DINER');text('combo',G.combo>1?`${G.combo}× streak`:'EARN · UNLOCK · GROW');
 text('personName',PEOPLE[o.person]);text('recipeName',o.recipe.name);text('orderNumber',`ORDER ${String(o.id).padStart(2,'0')}`);text('patienceLabel',`${Math.ceil(o.patience)}%`);$('patienceFill').style.width=o.patience+'%';$('patienceFill').style.background=o.patience<28?'#e56c55':o.patience<55?'#e8b346':'#79bf56';
 $('customerArt').style.backgroundPosition=(o.person*25)+'% 100%';$('customerArt').dataset.person=String(o.person);$('customerArt').setAttribute('aria-label',PEOPLE[o.person]+' at the counter');
 const stage=$('customerStage');stage.style.setProperty('--portrait-size',Math.max(0,Math.min(stage.clientWidth-4,stage.clientHeight-8))+'px');const walking=Math.min(1,Math.max(0,1-o.arrivalLeft/1400));stage.style.setProperty('--walk-progress',1-Math.pow(1-walking,3));const leaving=G.phase==='served'?Math.max(0,(1700-G.phaseLeft-400)/1300):G.phase==='left'?Math.max(0,1-G.phaseLeft/1400):0;stage.style.setProperty('--leave-progress',Math.min(1,leaving));
 stage.classList.toggle('walking',o.arrivalLeft>0);stage.classList.toggle('departing',G.phase==='served'||G.phase==='left');stage.classList.toggle('satisfied',G.phase==='served');
 $('customerArt').classList.toggle('impatient',o.patience<28&&G.phase==='playing');$('service').classList.toggle('arriving',o.arrivalLeft>0);$('service').classList.toggle('departing',G.phase==='served'||G.phase==='left');
 $('app').classList.toggle('paused',G.paused);$('app').classList.toggle('serving',G.phase==='served');
 const orderKey=o.id+':'+o.recipe.id;if(orderKey!==lastOrder){html('orderBurger',A.burger(o.recipe.layers,true));html('orderSides',(o.fries?`<span class="side-icon">${A.fries()}</span>`:'')+(o.drink?`<span class="side-icon">${A.drink()}</span>`:''));lastOrder=orderKey;}
 html('orderTabs',G.capacity>1?G.orders.map(v=>`<button type="button" data-action="customer" data-order="${v.id}" class="${o.id===v.id?'chosen':''}">${PEOPLE[v.person]}${G.ready(v)?' ✓':''}</button>`).join(''):'');$('orderTabs').hidden=G.capacity===1;
 html('recipeList',o.recipe.layers.map(id=>`<span data-needed="${id}" class="recipe-chip ${o.built.includes(id)?'added':''}">${o.built.includes(id)?'✓ ':''}${LABELS[id]}</span>`).join(''));
 text('orderExtras',(o.fries?'Fries'+(o.friesReady?' ✓':''):'No fries')+' · '+(o.drink?'Cola'+(o.drinkReady?' ✓':''):'No drink'));
 const buildKey=o.id+':'+o.built.join(',')+':'+o.friesReady+o.drinkReady;if(buildKey!==lastBuild){html('builtBurger',A.burger(o.built));html('readySides',(o.friesReady?`<span>${A.fries()}</span>`:'')+(o.drinkReady?`<span>${A.drink()}</span>`:''));lastBuild=buildKey;}
 text('buildLabel',o.built.length?`${o.built.length}/${o.recipe.layers.length} layers`:'Start with a bun base');
 document.querySelectorAll('[data-action="ingredient"]').forEach(b=>{const id=b.dataset.id,isMeat=id==='rawPatty'||id==='rawBacon',meat=id==='rawPatty'?'patty':'bacon';b.classList.toggle('suggested',isMeat?G.canAdd(meat):G.canAdd(id));b.classList.toggle('selected',isMeat&&G.selected===meat);b.setAttribute('aria-pressed',String(isMeat&&G.selected===meat));});
 document.querySelectorAll('.grill').forEach((el,i)=>{const g=G.grills[i],state=i>=G.burners?'locked':g?G.stage(g):'empty';el.dataset.stage=state;el.classList.toggle('place',!!G.selected&&state==='empty');const upgrade=SHOP.find(x=>x.id==='burner'+(i+1));const label=state==='locked'?`SHOP · $${upgrade.cost}`:state==='empty'?(G.selected?'PLACE HERE':'BURNER '+(i+1)):state==='ready'?'READY · TAP':state==='burned'?'BURNED · TOSS':`${state.toUpperCase()} ${Math.max(1,Math.ceil(((g.type==='patty'?5000:4000)-g.elapsed)/1000))}s`;el.querySelector('.grill-status').textContent=label;el.setAttribute('aria-label',`Burner ${i+1}: ${label}`);const key=g?g.type+state:state;if(el.dataset.art!==key){el.querySelector('.grill-art').innerHTML=g?A.food(g.type,state):state==='locked'?'<span class="lock-symbol">＋</span>':'';el.dataset.art=key;}el.querySelector('.progress i').style.width=g?Math.min(100,g.elapsed/(g.type==='patty'?5000:4000)*100)+'%':'0%';});
 for(const type of ['fries','drink']){const job=G.jobs[type],ready=job&&job.elapsed>=job.duration,progress=job?job.elapsed/job.duration:0,button=$(type+'Station'),locked=!G.hasStation(type);const state=locked?'locked':ready?'ready':job?'working':o[type+'Ready']?'collected':'idle';button.dataset.state=state;button.style.setProperty('--fill',Math.round(progress*100)+'%');const artKey=state+':'+(type==='drink'?Math.floor(progress*10):0);if(lastSideArt[type]!==artKey){$(type+'Machine').innerHTML=A.machine(type,progress);lastSideArt[type]=artKey;}const cost=SHOP.find(x=>x.id===(type==='fries'?'fryer':'drinkMachine')).cost;text(type+'Label',locked?`SHOP · $${cost}`:ready?'READY · COLLECT':job?(type==='fries'?'FRYING ':'FILLING ')+Math.max(1,Math.ceil((job.duration-job.elapsed)/1000))+'s':o[type+'Ready']?'ON TRAY ✓':o[type]?(type==='fries'?'START FRYER':'FILL COLA'):'NOT ORDERED');button.setAttribute('aria-label',(type==='fries'?'Fryer: ':'Drink station: ')+$(type+'Label').textContent);}
 const ready=G.ready()&&G.playable();$('serveBtn').classList.toggle('ready',ready);$('serveBtn').setAttribute('aria-disabled',String(!ready));text('serveBtn',G.phase==='served'?'SERVED ✓':`SERVE ${PEOPLE[o.person].toUpperCase()} →`);text('hint',G.hint());text('pauseBtn',G.paused?'▶':'Ⅱ');text('status',saveWarning||G.message);
 if(G.phase==='summary'&&lastPhase!=='summary'&&$('shopModal').hidden)showModal('summary');lastPhase=G.phase;
}
$('app').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b||saveConflict)return;let result;$('status').classList.remove('error');switch(b.dataset.action){case 'ingredient':result=G.pick(b.dataset.id);break;case 'grill':{const i=Number(b.dataset.index);if(i>=G.burners){openShop('burner'+(i+1));return;}result=G.grillTap(i);break;}case 'fries':case 'drink':{const type=b.dataset.action;if(!G.hasStation(type)){openShop(type==='fries'?'fryer':'drinkMachine');return;}result=G.side(type);break;}case 'serve':result=G.serve();break;case 'undo':result=G.undo();break;case 'customer':result=G.chooseOrder(Number(b.dataset.order));break;case 'shop':openShop();return;case 'pause':showModal('pause');return;case 'help':showModal('help');return;}render();save();if(result&&!result.ok)$('status').classList.add('error');});
$('modalPrimary').addEventListener('click',closeModal);$('expandBtn').addEventListener('click',()=>openShop());$('shopClose').addEventListener('click',closeShop);
$('shopFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;shopFilter=b.dataset.filter;renderShop();$('shopFilters').querySelector(`[data-filter="${shopFilter}"]`).focus();});
$('shopItems').addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(!b||b.disabled||saveConflict)return;const result=G.buy(b.dataset.buy);shopResult=result.message;save();render();renderShop();$('shopClose').focus();});
addEventListener('keydown',e=>{const dialog=!$('shopModal').hidden?$('shopModal'):!$('modal').hidden?$('modal'):null;if(e.key==='Escape'){e.preventDefault();if(!$('shopModal').hidden)closeShop();else if($('modal').hidden)showModal('pause');else if(!['welcome','summary','conflict'].includes(modalMode))closeModal();}if(e.key==='Tab'&&dialog){const buttons=[...dialog.querySelectorAll('button:not([disabled])')].filter(b=>!b.hidden&&b.getClientRects().length);if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(!G.paused)showModal('pause');}});addEventListener('pagehide',save);
addEventListener('storage',e=>{if(e.key===SAVE_KEY&&e.newValue!==lastSaved){saveConflict=true;G.paused=true;$('shopModal').hidden=true;showModal('conflict');}});
Object.defineProperty(root,'bbState',{get:()=>JSON.parse(JSON.stringify({...G,money:G.money,burners:G.burners}))});
let last=performance.now(),accum=0,saveAccum=0;function tick(now){const dt=Math.min(100,Math.max(0,now-last));last=now;const phase=G.phase,id=G.activeId;G.advance(dt);accum+=dt;saveAccum+=dt;if(accum>=80){render();accum=0;}if(phase!==G.phase||id!==G.activeId||saveAccum>=5000&&!G.paused){save();saveAccum=0;}requestAnimationFrame(tick);}
render();showModal(G.phase==='summary'?'summary':'welcome');requestAnimationFrame(tick);root.__BB_VERSION__='27.0';
})(globalThis);
