'use strict';
const assert=require('node:assert/strict');
const {Kitchen,SHOP,BASE}=require('./v28-model.js');
const A=require('./v28-art.js');
let n=0;
function test(name,fn){fn();console.log('PASS',++n,name);}
function open(){const g=new Kitchen();g.paused=false;g.advance(2200);return g;}
function fund(g){g.cashCents=g.earnedCents=500000;g.served=25;}
function cook(g,type){assert(g.pick(type==='patty'?'rawPatty':'rawBacon').ok);assert(g.grillTap(0).ok);g.advance(type==='patty'?5000:4000);assert(g.grillTap(0).ok);}
function build(g){assert(g.pick('bottomBun').ok);cook(g,'patty');for(const id of g.active.recipe.layers.slice(2,-1).reverse()){if(id==='bacon')cook(g,id);else assert(g.pick(id).ok);}assert(g.pick('topBun').ok);for(const t of ['fries','drink'])if(g.active[t]){assert(g.side(t).ok);g.advance(t==='fries'?6000:3000);assert(g.side(t).ok);}}
test('Fresh game: only buns and meat, one burner, $0, no sides',()=>{const g=open();assert.deepEqual(g.active.recipe.layers,BASE);assert.equal(g.burners,1);assert.equal(g.cashCents,0);assert.equal(g.capacity,1);assert(!g.active.fries&&!g.active.drink);assert.equal(g.menu().length,1);});
test('Customer arrival is cozy and costs no patience',()=>{const g=new Kitchen();g.paused=false;assert(!g.pick('bottomBun').ok);g.advance(1000);assert.equal(g.active.patience,100);assert.equal(g.active.arrivalLeft,1200);g.advance(1200);assert(g.pick('bottomBun').ok);});
test('Locked ingredients cannot be selected or placed',()=>{const g=open();for(const id of ['cheese','bacon','rawBacon','sauce','lettuce','tomato','pickles','onion']){assert(!g.pick(id).ok);assert(!g.canAdd(id));}assert.deepEqual(g.active.built,[]);});
test('Extra burners and machines require purchase',()=>{const g=open();g.pick('rawPatty');for(let i=1;i<4;i++)assert(!g.grillTap(i).ok);assert(g.grillTap(0).ok);assert(!g.side('fries').ok);assert(!g.side('drink').ok);});
test('Raw meat must cook before stacking',()=>{const g=open();g.pick('bottomBun');assert(!g.pick('patty').ok);g.pick('rawPatty');g.grillTap(0);g.advance(4999);assert(!g.grillTap(0).ok);g.advance(1);assert(g.grillTap(0).ok);});
test('Buns cannot close an incomplete burger; no double-serving payout',()=>{const g=open();g.pick('bottomBun');assert(!g.pick('topBun').ok);cook(g,'patty');g.pick('topBun');assert(g.serve().ok);const amount=g.cashCents;assert(!g.serve().ok);assert.equal(g.cashCents,amount);assert(Number.isSafeInteger(amount));assert.equal(g.earnedCents,amount);});
test('Cannot buy unaffordable or unknown upgrades',()=>{const g=open();for(const id of ['cheese','burner2','not-real'])assert(!g.buy(id).ok);assert.equal(g.cashCents,0);assert.deepEqual(g.unlocks,[]);});
test('Cheese affordable after three basic orders using actual earnings',()=>{const g=open();for(let i=0;i<3;i++){build(g);assert(g.serve().ok);g.advance(1700);g.advance(2200);}assert(g.cashCents>=2000);const before=g.cashCents;assert(g.buy('cheese').ok);assert.equal(g.cashCents,before-2000);const cash=g.cashCents;assert(!g.buy('cheese').ok);assert.equal(g.cashCents,cash);});
for(const item of SHOP)test('Purchase '+item.id+' deducts once and unlocks exactly',()=>{const g=open();fund(g);for(const x of SHOP){if(x.id===item.id)break;if(item.requires?.includes(x.id)||x.group==='Equipment'||x.group==='Store expansion')g.buy(x.id);}const before=g.cashCents;assert(g.buy(item.id).ok);assert(g.owns(item.id));assert.equal(g.cashCents,before-item.cost*100);assert(!g.buy(item.id).ok);assert.equal(g.cashCents,before-item.cost*100);});
test('Purchase leaves existing ticket unchanged',()=>{const g=open();fund(g);const ticket=JSON.stringify(g.active);g.buy('cheese');g.buy('fryer');assert.equal(JSON.stringify(g.active),ticket);const next=g.makeOrder();assert(next.recipe.layers.includes('cheese'));assert(next.fries);});
test('Every combination of owned toppings generates only unlocked menu ingredients',()=>{const ingredients=SHOP.filter(i=>i.group==='Ingredients');for(let mask=0;mask<128;mask++){const g=open();fund(g);for(let i=0;i<7;i++)if(mask&(1<<i))g.buy(ingredients[i].id);for(const r of g.menu()){assert(r.layers.every(id=>g.hasIngredient(id)));const shown=[...A.burger(r.layers,true).matchAll(/data-layer="([^"]+)"/g)].map(x=>x[1]);assert.deepEqual(shown,r.layers);}for(let k=0;k<8;k++){const o=g.makeOrder();assert(o.recipe.layers.every(id=>g.hasIngredient(id)));assert(!o.fries&&!o.drink);}}});
test('All unlocked recipes and side combinations can be built with one burner',()=>{const g=open();fund(g);for(const x of SHOP.filter(x=>x.group==='Ingredients'||['fryer','drinkMachine'].includes(x.id)))g.buy(x.id);const menu=g.menu();for(const recipe of menu)for(const [fries,drink] of [[false,false],[true,false],[false,true],[true,true]]){g.phase='playing';g.active.recipe=recipe;g.active.built=[];g.active.patience=100;g.active.arrivalLeft=0;Object.assign(g.active,{fries,drink,friesReady:false,drinkReady:false});assert(!g.serve().ok);build(g);assert(g.ready());assert(g.serve().ok);}});
test('Burner prerequisites and expansion meal thresholds are enforced',()=>{const g=open();fund(g);assert(!g.buy('burner3').ok);assert(!g.buy('burner4').ok);assert(!g.buy('counter2').ok);g.buy('burner2');g.served=9;assert(!g.buy('counter2').ok);g.served=10;assert(g.buy('counter2').ok);assert.equal(g.capacity,1);g.phase='summary';g.continueShift();assert.equal(g.capacity,2);assert.equal(g.burners,2);});
test('Shop pause freezes cooking, filling, patience, arrival and departure',()=>{const g=open();fund(g);g.buy('drinkMachine');g.active.drink=true;g.side('drink');g.pick('rawPatty');g.grillTap(0);g.paused=true;const before=JSON.stringify(g.snapshot());g.advance(60000);assert.equal(JSON.stringify(g.snapshot()),before);});
test('Save restores exact money, unlocks, burger, grills and partial side jobs',()=>{const g=open();fund(g);g.buy('cheese');g.buy('drinkMachine');g.active.drink=true;g.side('drink');g.pick('bottomBun');g.pick('rawPatty');g.grillTap(0);g.advance(2000);const restored=new Kitchen(g.snapshot());assert(restored.loaded);assert(restored.paused);assert.deepEqual(restored.snapshot(),g.snapshot());});
test('Restoring served-order transition does not allow payout twice',()=>{const g=open();build(g);g.serve();const restored=new Kitchen(g.snapshot());restored.paused=false;assert.equal(restored.phase,'served');assert(!restored.serve().ok);const amount=restored.cashCents;restored.advance(1700);assert.equal(restored.cashCents,amount);assert.notEqual(restored.active.id,g.active.id);});
test('House special survives purchase of another ingredient and reload',()=>{const g=open();fund(g);g.buy('cheese');g.buy('lettuce');g.active.recipe=g.menu().find(r=>r.id.startsWith('house-'));g.pick('bottomBun');const order=JSON.stringify(g.active);g.buy('tomato');const restored=new Kitchen(g.snapshot());assert.equal(JSON.stringify(restored.active),order);});
test('Corrupted and unknown-version saves safely start a new stand',()=>{for(const s of [null,{},[],{version:26},{version:27,unlocks:[],cashCents:-1,earnedCents:0}]){const g=new Kitchen(s);assert.equal(g.burners,1);assert.equal(g.cashCents,0);assert.equal(g.orders.length,1);}});
test('Invalid saved orders are discarded without creating impossible recipes',()=>{const g=open();const s=g.snapshot();s.orders[0].recipe.layers=['topBun','bacon'];const r=new Kitchen(s);assert.deepEqual(r.active.recipe.layers,BASE);assert(!r.active.fries);});
test('Five orders pause for summary and next shift retains upgrades/cash',()=>{const g=open();for(let i=0;i<5;i++){build(g);g.serve();g.advance(1700);g.advance(2200);}assert.equal(g.phase,'summary');assert(g.buy('cheese').ok);const cash=g.cashCents;assert(g.continueShift());assert.equal(g.shift,2);assert.equal(g.cashCents,cash);assert(g.owns('cheese'));assert.equal(g.capacity,1);});
test('Side ownership is stable when active customer changes',()=>{const g=open();fund(g);for(const id of ['burner2','counter2','drinkMachine','fryer'])g.buy(id);g.phase='summary';g.continueShift();g.advance(2200);const a=g.active,b=g.orders[1];a.fries=true;b.drink=true;g.side('fries');g.chooseOrder(b.id);g.side('drink');g.advance(6000);assert(g.side('fries').ok);assert(a.friesReady&&!b.friesReady);assert(g.side('drink').ok);assert(b.drinkReady&&!a.drinkReady);});
test('Timeout exit completes before replacement and removes stale jobs',()=>{const g=open();fund(g);g.buy('fryer');g.active.fries=true;g.side('fries');const id=g.activeId;g.advance(200000);assert.equal(g.phase,'left');assert.equal(g.activeId,id);g.advance(2200);assert.notEqual(g.activeId,id);assert.equal(g.jobs.fries,null);assert.equal(g.active.patience,100);});
test('Burned meat is discarded and undo affects only burger',()=>{const g=open();g.pick('bottomBun');g.pick('rawPatty');g.grillTap(0);g.advance(15000);assert.equal(g.stage(g.grills[0]),'burned');assert(!g.grillTap(0).ok);assert.equal(g.grills[0],null);assert.deepEqual(g.active.built,['bottomBun']);g.undo();assert.deepEqual(g.active.built,[]);});
test('Ready food does not burn while an entrance blocks input',()=>{const g=open();g.pick('bottomBun');g.pick('rawPatty');g.grillTap(0);g.advance(14500);g.active.arrivalLeft=2200;g.advance(2200);assert.equal(g.stage(g.grills[0]),'ready');assert(g.grillTap(0).ok);});
console.log(`\n${n} v28 model/renderer tests passed`);
