'use strict';
const assert=require('node:assert/strict');
const {Kitchen,SHOP,TIMING}=require('./v31-model.js');
const {foot,solve,character}=require('./v31-customers.js');
let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
function fresh(){const g=new Kitchen();g.paused=false;g.advance(TIMING.arrival);return g;}
function complete(g){for(const id of g.active.recipe.layers){if(id==='patty'||id==='bacon'){assert(g.pick(id==='patty'?'rawPatty':'rawBacon').ok);assert(g.grillTap(0).ok);g.advance(id==='patty'?5000:4000);assert(g.grillTap(0).ok);}else assert(g.pick(id).ok);}for(const t of ['fries','drink'])if(g.active[t]){assert(g.side(t).ok);g.advance(t==='fries'?6000:3000);assert(g.side(t).ok);}assert(g.ready());}
function money(g){return [g.cashCents,g.earnedCents,g.score,g.served,g.shiftServed];}
test('starter equipment and saved sound/economy boundaries',()=>{const g=fresh();assert.equal(g.burners,1);assert.equal(g.money,0);assert.deepEqual(g.active.recipe.layers,['bottomBun','patty','topBun']);assert.equal(g.snapshot().version,27);});
test('cash appears at hand release, never at serve tap',()=>{const g=fresh();complete(g);const before=money(g);assert(g.serve().ok);assert.equal(g.phase,'paying');assert.deepEqual(money(g),before);g.advance(TIMING.deposit-1);assert.deepEqual(money(g),before);g.advance(1);assert.equal(g.cashCents,g.payment.amount);assert.equal(g.served,1);assert(g.payment.paid);});
test('repeated taps and credit calls cannot duplicate payout',()=>{const g=fresh();complete(g);g.serve();assert(!g.serve().ok);g.advance(1400);const before=money(g);assert(!g.serve().ok);assert(!g.creditPayment());assert.deepEqual(money(g),before);g.advance(3000);assert.deepEqual(money(g),before);});
test('incomplete burger never starts a payment',()=>{const g=fresh();assert(!g.serve().ok);assert.equal(g.phase,'playing');assert.equal(g.payment,null);});
test('pause freezes payment and delayed credit',()=>{const g=fresh();complete(g);g.serve();g.advance(1000);g.paused=true;const s=g.snapshot();g.advance(99999);assert.deepEqual(g.snapshot(),s);g.paused=false;g.advance(350);assert(g.payment.paid);});
test('restore before deposit resumes exactly one payout',()=>{let g=fresh();complete(g);g.serve();g.advance(1000);const p=g.payment.amount;g=new Kitchen(g.snapshot());assert.equal(g.phase,'paying');assert.equal(g.money,0);g.paused=false;g.advance(350);assert.equal(g.cashCents,p);});
test('restore after deposit cannot credit again',()=>{let g=fresh();complete(g);g.serve();g.advance(1500);const before=money(g);g=new Kitchen(g.snapshot());assert.equal(g.phase,'paying');g.paused=false;g.advance(5000);assert.deepEqual(money(g),before);});
test('last order restores paying instead of skipping the handoff',()=>{let g=fresh();g.shiftServed=4;g.served=4;complete(g);g.serve();g.advance(1400);g=new Kitchen(g.snapshot());assert.equal(g.phase,'paying');g.paused=false;g.advance(4000);assert.equal(g.phase,'summary');assert.equal(g.served,5);});
test('legacy v29 already-paid order is not paid twice',()=>{let g=fresh();complete(g);const s=g.snapshot();s.cashCents=700;s.earnedCents=700;s.served=1;s.shiftServed=1;s.phase='served';s.phaseLeft=1200;delete s.payment;g=new Kitchen(s);g.paused=false;g.advance(3000);assert.equal(g.cashCents,700);assert.equal(g.served,1);});
test('clock can cross deposit and exit without a skipped/duplicate payment',()=>{const g=fresh();complete(g);g.serve();const amount=g.payment.amount;g.advance(7000);assert.equal(g.cashCents,amount);assert.equal(g.served,1);assert.equal(g.phase,'playing');assert.equal(g.active.id,2);});
test('payment precedes walking away and next customer',()=>{const g=fresh();complete(g);g.serve();const id=g.active.id;g.advance(2200);assert.equal(g.phase,'served');assert.equal(g.active.id,id);assert(g.payment.paid);g.advance(2200);assert.equal(g.phase,'playing');assert.notEqual(g.active.id,id);assert.equal(g.payment,null);});
test('shop cannot spend promised money before deposit',()=>{const g=fresh();g.cashCents=1500;complete(g);g.serve();assert(!g.buy('cheese').ok);g.advance(1350);assert(g.buy('cheese').ok);});
test('wrong ingredients, premature top and raw meat direct placement rejected',()=>{const g=fresh();assert(!g.pick('cheese').ok);assert(!g.pick('topBun').ok);assert(!g.pick('patty').ok);assert.deepEqual(g.active.built,[]);});
test('burn and undo work in the new model',()=>{const g=fresh();g.pick('bottomBun');g.pick('rawPatty');g.grillTap(0);g.advance(16000);assert.equal(g.stage(g.grills[0]),'burned');g.grillTap(0);assert.equal(g.grills[0],null);g.undo();assert.deepEqual(g.active.built,[]);});
test('arrival protects READY food and preserves input lock',()=>{const g=new Kitchen();g.grills[0]={type:'patty',elapsed:14990};g.paused=false;assert(!g.pick('bottomBun').ok);g.advance(2400);assert.equal(g.grills[0].elapsed,14990);assert(g.playable());});
test('all 128 topping combinations only generate achievable orders',()=>{const ids=SHOP.filter(x=>x.group==='Ingredients').map(x=>x.id);for(let mask=0;mask<128;mask++){const g=fresh();g.cashCents=1000000;ids.forEach((id,i)=>{if(mask&(1<<i))assert(g.buy(id).ok);});for(const r of g.menu())assert(r.layers.every(id=>g.hasIngredient(id)));complete(g);const old=g.cashCents;g.serve();g.advance(1350);assert(g.cashCents>old);assert.equal(g.served,1);}});
test('every fully unlocked recipe with every sides combination pays once',()=>{const g=fresh();g.cashCents=10000000;for(const x of SHOP.filter(x=>!x.id.startsWith('counter')))assert(g.buy(x.id).ok);for(const r of g.menu())for(let n=0;n<4;n++){g.phase='playing';g.active.recipe=r;g.active.built=[];g.active.arrivalLeft=0;g.active.patience=100;g.active.fries=!!(n&1);g.active.drink=!!(n&2);g.active.friesReady=false;g.active.drinkReady=false;complete(g);const count=g.served;g.serve();g.advance(1400);assert.equal(g.served,count+1);assert(g.payment.paid);}});
test('multi-customer payment remains owned by served customer',()=>{const g=fresh();g.cashCents=1000000;g.served=20;g.buy('burner2');g.buy('counter2');g.phase='summary';g.continueShift();g.advance(2400);complete(g);g.serve();const id=g.active.id;assert(!g.chooseOrder(g.orders[1].id).ok);g.advance(1350);assert.equal(g.payment.orderId,id);});
test('stance feet have zero analytical world-space slide in both directions',()=>{for(const offset of [0,.5])for(let d=2;d<500;d+=.3){const a=foot(d,offset),b=foot(d+.1,offset);if(a.stance&&b.stance&&b.phase>a.phase){assert(Math.abs((d+a.x)-(d+.1+b.x))<1e-8);assert(Math.abs((-d-a.x)-(-d-.1-b.x))<1e-8);assert.equal(a.lift,0);}}});
test('limb solver returns finite feasible joint positions',()=>{for(let d=0;d<1000;d+=2){const f=foot(d,0),p=solve(96,299,96+f.x,431-f.lift,68,66,-1);assert(Object.values(p).every(Number.isFinite));assert(Math.abs(Math.hypot(p.kx-96,p.ky-299)-68)<1e-7);}});
test('each character has elbows, ankles and independently animated face patches',()=>{for(let i=0;i<5;i++){const s=character(i);for(const marker of ['leftElbow','rightElbow','leftFoot','rightFoot','data-eye','data-mouth','head-frame'])assert(s.includes(marker));assert(!s.includes('undefined'));}});
console.log(`\n${passed} v31 test groups passed`);
