'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');const {Kitchen,SHOP}=require('./v32-model.js');const Prior=require('./v31-model.js').Kitchen;let passed=0;function t(n,f){f();passed++;console.log('PASS '+n)}
function ready(g){g.paused=false;g.advance(2400);for(const id of g.active.recipe.layers){if(['patty','bacon'].includes(id)){assert(g.pick(id==='patty'?'rawPatty':'rawBacon').ok);assert(g.grillTap(0).ok);g.advance(id==='patty'?5000:4000);assert(g.grillTap(0).ok)}else assert(g.pick(id).ok)}for(const x of ['fries','drink'])if(g.active[x]){assert(g.side(x).ok);g.advance(6000);assert(g.side(x).ok)}assert(g.ready())}
t('new stand has Eddie, only three basic ingredients, one burner and no sides',()=>{const g=new Kitchen();assert.equal(g.active.person,2);assert.equal(g.burners,1);assert.deepEqual(g.active.recipe.layers,['bottomBun','patty','topBun']);assert.equal(g.money,0);assert.equal(g.active.fries,false);assert.equal(g.active.drink,false)});
t('current v31 saved person, ingredients, cash and shift migrate unchanged',()=>{const g=new Prior();g.cashCents=100000;g.earnedCents=100000;g.buy('cheese');g.buy('sauce');g.buy('burner2');g.active.person=3;g.shift=4;const s=g.snapshot(),n=new Kitchen(s);assert.deepEqual(n.snapshot(),s);assert.equal(n.active.person,3)});
t('no money credited on Serve; exactly once on deposit',()=>{const g=new Kitchen();ready(g);g.serve();assert.equal(g.money,0);g.advance(1349);assert.equal(g.money,0);g.advance(1);assert(g.money>0);const cents=g.cashCents;g.serve();g.advance(100);assert.equal(g.cashCents,cents)});
t('pending payment save survives both sides of deposit',()=>{let g=new Kitchen();ready(g);g.serve();g.advance(1000);g=new Kitchen(g.snapshot());g.paused=false;g.advance(350);const cash=g.cashCents;g=new Kitchen(g.snapshot());g.paused=false;g.advance(5000);assert.equal(g.cashCents,cash);assert.equal(g.served,1)});
t('pause and shopping preserve cash handoff timer',()=>{const g=new Kitchen();ready(g);g.serve();g.advance(1000);g.paused=true;const s=g.snapshot();g.advance(90000);assert.deepEqual(g.snapshot(),s)});
t('one burner cannot be bypassed by hidden button calls',()=>{const g=new Kitchen();g.paused=false;g.advance(2400);g.pick('rawPatty');assert(!g.grillTap(1).ok);assert.equal(g.grills[1],null)});
t('all 128 topping sets produce only possible orders',()=>{const ids=SHOP.filter(x=>x.group==='Ingredients').map(x=>x.id);for(let mask=0;mask<128;mask++){const g=new Kitchen();g.cashCents=1000000;ids.forEach((id,i)=>{if(mask&(1<<i))g.buy(id)});for(const r of g.menu())assert(r.layers.every(id=>g.hasIngredient(id)));ready(g);g.serve();g.advance(1400);assert.equal(g.served,1)}});
t('buying does not change an existing ticket',()=>{const g=new Kitchen();g.cashCents=100000;const r=JSON.stringify(g.active.recipe);g.buy('cheese');assert.equal(JSON.stringify(g.active.recipe),r);g.replaceOrder(g.activeId);assert(g.active.recipe.layers.includes('cheese'))});
t('all production links exist',()=>{const html=fs.readFileSync('index.html','utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g))assert(fs.existsSync(m[1].split('?')[0]),m[1])});
t('texture rectangles have independent bounds and gutters',()=>{const m=JSON.parse(fs.readFileSync('stand-art-v32.json'));for(const [k,[x,y,w,h]] of Object.entries(m).filter(([k])=>k!=='_size')){assert(x>=2&&y>=2&&w>0&&h>0);assert(x+w<=m._size[0]&&y+h<=m._size[1],k)}});
t('save and sound keys/files stay unchanged',()=>{assert(fs.readFileSync('v32-ui.js','utf8').includes("const SAVE_KEY='bens-burgers.v27.save'"));const html=fs.readFileSync('index.html','utf8');assert(html.includes('sound-v29.js?v=29.0'));assert(!html.includes('v31-customers.js'));assert(html.includes('v32-customers.js'))});
console.log(passed+' v32 groups passed');
